// Generated by design-engine /design-settings-page
// Adapter: obsidian-css
//
// Drop this into your plugin's main.ts or a separate settings.ts file.
// Register the tab in your plugin's onload() with:
//   this.addSettingTab(new DesignEngineSettingsTab(this.app, this));
//
// References:
// - Obsidian PluginSettingTab API: https://docs.obsidian.md/Plugins/Releasing/Plugin+settings
// - design-engine token system: see design-engine skill

import { App, PluginSettingTab, Setting, Plugin } from 'obsidian';

interface DesignEngineSettings {
  brand: string;
  font: string;
  // Add more tokens as needed
}

const DEFAULT_SETTINGS: DesignEngineSettings = {
  brand: '',  // empty = inherit Obsidian's --interactive-accent
  font: 'Inter',
};

export class DesignEngineSettingsTab extends PluginSettingTab {
  plugin: Plugin & { settings: DesignEngineSettings; saveSettings: () => Promise<void> };

  constructor(app: App, plugin: any) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h2', { text: 'Design Engine Settings' });

    new Setting(containerEl)
      .setName('Brand color')
      .setDesc('Override the active brand accent. Leave blank to inherit Obsidian\'s theme.')
      .addText(text => text
        .setPlaceholder('#635BFF or empty')
        .setValue(this.plugin.settings.brand)
        .onChange(async (value) => {
          this.plugin.settings.brand = value;
          await this.plugin.saveSettings();
          this.applyBrand(value);
        }));

    new Setting(containerEl)
      .setName('Font')
      .setDesc('Font family for plugin UI.')
      .addDropdown(dropdown => dropdown
        .addOptions({
          'Inter': 'Inter',
          'Pretendard': 'Pretendard',
          'Geist': 'Geist',
          'DM Sans': 'DM Sans',
          'system-ui': 'System default',
        })
        .setValue(this.plugin.settings.font)
        .onChange(async (value) => {
          this.plugin.settings.font = value;
          await this.plugin.saveSettings();
          this.applyFont(value);
        }));
  }

  private applyBrand(color: string) {
    const root = document.querySelector(':root') as HTMLElement;
    if (color) {
      root.style.setProperty('--de-brand', color);
    } else {
      root.style.removeProperty('--de-brand');
    }
  }

  private applyFont(font: string) {
    document.body.style.setProperty('--de-font-family', font);
  }
}
