// Generated by design-engine /design-settings-page
// Adapter: obsidian-css
//
// Drop this into your plugin's main.ts or a separate settings.ts file.
// Register the tab in your plugin's onload() with:
//   this.addSettingTab(new DesignEngineSettingsTab(this.app, this));

import { App, PluginSettingTab, Setting, Plugin } from 'obsidian';

type TokenValue = { $value: string };
type TokenGroup = { $type?: string; [name: string]: TokenValue | string | undefined };
type Tokens = { [group: string]: TokenGroup };

const GROUP_TO_PREFIX: Record<string, string> = {
  color: '', radius: 'radius', font: 'font',
  shadow: 'shadow', spacing: 'spacing', motion: 'duration',
};

const COLOR_RE = /^#(?:[0-9a-f]{3,8})$/i;

function tokenKeyToCssName(group: string, key: string): string {
  const prefix = GROUP_TO_PREFIX[group];
  if (prefix === undefined) return key;
  if (prefix === '') return key;
  if (key === 'default') return prefix;
  return `${prefix}-${key}`;
}

function isColorValue(value: string): boolean {
  return COLOR_RE.test(value);
}

export interface DesignEngineSettings {
  tokens: Tokens;
}

export const DEFAULT_SETTINGS: DesignEngineSettings = {
  tokens: {},
};

export class DesignEngineSettingsTab extends PluginSettingTab {
  plugin: Plugin & { settings: DesignEngineSettings; saveSettings: () => Promise<void> };

  constructor(app: App, plugin: any) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h2', { text: 'Design Engine Settings' });

    const tokens = this.plugin.settings.tokens;
    if (!tokens || Object.keys(tokens).length === 0) {
      containerEl.createEl('p', {
        text: 'No tokens found. Run /design-init to set up your design system.',
      });
      return;
    }

    for (const [group, groupObj] of Object.entries(tokens)) {
      containerEl.createEl('h3', {
        text: group.charAt(0).toUpperCase() + group.slice(1),
      });

      for (const [key, val] of Object.entries(groupObj)) {
        if (key === '$type') continue;
        if (!val || typeof val !== 'object' || !('$value' in val)) continue;
        const tokenVal = val as TokenValue;
        const cssName = tokenKeyToCssName(group, key);
        const valueIsColor = groupObj.$type === 'color' || isColorValue(tokenVal.$value);

        new Setting(containerEl)
          .setName(`--${cssName}`)
          .addText(text => text
            .setValue(tokenVal.$value)
            .onChange(async (value) => {
              (this.plugin.settings.tokens[group][key] as TokenValue) = { $value: value };
              await this.plugin.saveSettings();
              this.applyToken(cssName, value);
            }));
      }
    }
  }

  private applyToken(cssName: string, value: string) {
    const root = document.querySelector(':root') as HTMLElement;
    if (value) {
      root.style.setProperty(`--${cssName}`, value);
    } else {
      root.style.removeProperty(`--${cssName}`);
    }
  }
}
