// Generated by design-engine /design-settings-page
// SvelteKit endpoint: GET /__design/api/google-fonts
// Dev-only — gated by `dev` from $app/environment. Returns 404 in production.
//
// Installed at: src/routes/__design/api/google-fonts/+server.ts
// Companion files:
//   - $lib/server/design-engine/google-fonts-catalog.ts (helper, server-only)
//
// Why this is a separate file from the tokens API: SvelteKit uses
// file-based routing — one +server.ts owns one route path. The Google
// Fonts proxy lives at /__design/api/google-fonts, the tokens API
// lives at /__design/api/tokens, so they need separate files.

import { json, error } from '@sveltejs/kit';
import { dev } from '$app/environment';
import type { RequestHandler } from './$types';
import { fetchGoogleFontsCatalog } from '$lib/server/design-engine/google-fonts-catalog';

export const GET: RequestHandler = async () => {
  if (!dev) error(404);

  try {
    const fonts = await fetchGoogleFontsCatalog();
    return json(fonts);
  } catch {
    return json(
      { ok: false, error: 'catalog_unavailable', message: 'Failed to load Google Fonts catalog' },
      { status: 503 },
    );
  }
};
