// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// SvelteKit endpoint: GET/POST /__design/api/tokens
// Dev-only — gated by `dev` from $app/environment. Returns 404 in production.
//
// Installed at: src/routes/__design/api/tokens/+server.ts
// Companion files:
//   - $lib/server/design-engine/theme-io.ts (helper, server-only)
//   - src/routes/__design/+page.svelte (UI)

import { json, error } from '@sveltejs/kit';
import { dev } from '$app/environment';
import type { RequestHandler } from './$types';
import { resolve } from 'node:path';
import { readFile, writeFile } from 'node:fs/promises';
import {
  writeTokensToCss,
  type Tokens,
} from '$lib/server/design-engine/theme-io';

function validateW3CShape(body: unknown): asserts body is Tokens {
  if (!body || typeof body !== 'object') throw new Error('Body must be a token object');
  for (const [group, groupObj] of Object.entries(body as Record<string, unknown>)) {
    if (!groupObj || typeof groupObj !== 'object') throw new Error(`Group "${group}" must be an object`);
    for (const [key, val] of Object.entries(groupObj as Record<string, unknown>)) {
      if (key === '$type') continue;
      if (!val || typeof val !== 'object' || !('$value' in (val as Record<string, unknown>))) {
        throw new Error(`Token "${group}.${key}" must have a $value property`);
      }
    }
  }
}

async function handleGetTokens({ projectRoot }: { projectRoot: string }): Promise<Tokens> {
  const tokensPath = resolve(projectRoot, 'tokens.json');
  const raw = await readFile(tokensPath, 'utf8');
  return JSON.parse(raw);
}

async function handlePostTokens({ projectRoot, body }: { projectRoot: string; body: unknown }): Promise<{ tokens: Tokens }> {
  validateW3CShape(body);
  const tokens = body as Tokens;

  const tokensPath = resolve(projectRoot, 'tokens.json');
  await writeFile(tokensPath, JSON.stringify(tokens, null, 2) + '\n', 'utf8');

  const configPath = resolve(projectRoot, '.design-rules', 'config.json');
  const config = JSON.parse(await readFile(configPath, 'utf8'));
  const themeFile = config.themeFile;

  if (themeFile) {
    const themePath = resolve(projectRoot, themeFile);
    const existingCss = await readFile(themePath, 'utf8');
    const newCss = writeTokensToCss(tokens, { existing: existingCss });
    await writeFile(themePath, newCss, 'utf8');
  }

  return { tokens };
}

export const GET: RequestHandler = async () => {
  if (!dev) error(404);

  try {
    const tokens = await handleGetTokens({ projectRoot: process.cwd() });
    return json(tokens);
  } catch (e) {
    return json({ error: 'read_failed', message: String(e) }, { status: 409 });
  }
};

export const POST: RequestHandler = async ({ request }) => {
  if (!dev) error(404);

  let parsed: unknown;
  try {
    parsed = await request.json();
  } catch {
    return json({ ok: false, error: 'bad_request', message: 'Invalid JSON' }, { status: 400 });
  }

  try {
    const result = await handlePostTokens({ projectRoot: process.cwd(), body: parsed });
    return json({ ok: true, tokens: result.tokens });
  } catch (e) {
    return json({ ok: false, error: 'validation_failed', message: String(e) }, { status: 422 });
  }
};
