// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// SvelteKit endpoint: GET/POST /__design/api/tokens
// Dev-only — gated by `dev` from $app/environment. Returns 404 in production.
//
// Installed at: src/routes/__design/api/tokens/+server.ts
// Companion files:
//   - $lib/server/design-engine/theme-io.ts (helper, server-only)
//   - src/routes/__design/+page.svelte (UI)

import { json, error } from '@sveltejs/kit';
import { dev } from '$app/environment';
import type { RequestHandler } from './$types';
import { resolve } from 'node:path';
import {
  readTokens,
  writeTokens,
  writeFontImports,
  buildGoogleFontsUrl,
  type Mode,
  type ColorTokens,
} from '$lib/server/design-engine/theme-io';

const DEFAULT_THEME = 'src/lib/styles/theme.css';
const DEFAULT_FONTS = 'src/lib/styles/fonts.css';

function themePath(): string {
  return resolve(process.cwd(), DEFAULT_THEME);
}

function fontsPath(): string {
  return resolve(process.cwd(), DEFAULT_FONTS);
}

export const GET: RequestHandler = async () => {
  if (!dev) error(404);

  const result = await readTokens(themePath());
  if (!result.ok) {
    return json({ error: result.error, message: result.message }, { status: 409 });
  }
  return json(result.tokens);
};

type PostBody = {
  mode: Mode;
  colors: ColorTokens;
  font?: string;
  fontImport?: { name: string; weights?: number[]; axisRange?: string } | null;
};

export const POST: RequestHandler = async ({ request }) => {
  if (!dev) error(404);

  let parsed: PostBody;
  try {
    parsed = await request.json();
  } catch {
    return json({ ok: false, error: 'bad_request', message: 'Invalid JSON' }, { status: 400 });
  }

  const writeResult = await writeTokens(themePath(), parsed.mode, parsed.colors, parsed.font);
  if (!writeResult.ok) {
    return json(
      { ok: false, error: writeResult.error, message: writeResult.message },
      { status: 409 },
    );
  }

  if (parsed.fontImport && parsed.fontImport.name) {
    const importUrl = buildGoogleFontsUrl(
      parsed.fontImport.name,
      parsed.fontImport.weights,
      parsed.fontImport.axisRange,
    );
    const fontResult = await writeFontImports(fontsPath(), [
      { name: parsed.fontImport.name, url: importUrl },
    ]);
    if (!fontResult.ok) {
      return json(
        {
          ok: false,
          error: 'font_write_failed',
          message: fontResult.message,
          tokens: writeResult.tokens,
        },
        { status: 207 },
      );
    }
  } else if (parsed.fontImport === null) {
    const fontResult = await writeFontImports(fontsPath(), []);
    if (!fontResult.ok) {
      return json(
        {
          ok: false,
          error: 'font_write_failed',
          message: fontResult.message,
          tokens: writeResult.tokens,
        },
        { status: 207 },
      );
    }
  }

  return json({ ok: true, tokens: writeResult.tokens });
};
