<script lang="ts">
  // Generated by design-engine /design-component (or /design-pattern)
  // Adapter: sveltekit
  interface Props {
    title?: string;
    className?: string;
    children?: import('svelte').Snippet;
  }
  let { title, className = '', children }: Props = $props();
</script>

<div data-slot="<component-name-kebab>" class="base-classes-here {className}">
  {@render children?.()}
</div>
