<script lang="ts">
  // Generated by design-engine /design-settings-page
  // Adapter: sveltekit
  // Dev-only — gate with `if (!import.meta.env.DEV) error(404);` in +page.ts
  //
  // Note: This is a dev-only token viewer. Edits produce a copyable CSS snippet —
  //       paste it into your theme.css to apply. Live write-back is a v0.x feature.

  import { browser } from '$app/environment';

  type TokenSet = {
    brand: string;
    primary: string;
    background: string;
    card: string;
    foreground: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
    font: string;
  };

  let tokens = $state<TokenSet>({
    brand: '#721FE5',
    primary: '#030213',
    background: '#FAFAFA',
    card: '#FFFFFF',
    foreground: '#2A2A2A',
    destructive: '#d4183d',
    success: '#6B9B7A',
    warning: '#D97706',
    info: '#3B82F6',
    font: 'Inter',
  });

  let cssOutput = $derived(`:root {
  --brand: ${tokens.brand};
  --primary: ${tokens.primary};
  --background: ${tokens.background};
  --card: ${tokens.card};
  --foreground: ${tokens.foreground};
  --destructive: ${tokens.destructive};
  --success: ${tokens.success};
  --warning: ${tokens.warning};
  --info: ${tokens.info};
  --font-primary: ${tokens.font}, system-ui, sans-serif;
}`);

  function copyCss() {
    if (!browser) return;
    navigator.clipboard.writeText(cssOutput);
    alert('CSS copied — paste into your theme.css :root block.');
  }

  function downloadCss() {
    if (!browser) return;
    const blob = new Blob([cssOutput], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'theme.css';
    a.click();
    URL.revokeObjectURL(url);
  }

  const colorKeys = ['brand', 'primary', 'background', 'card', 'foreground', 'destructive', 'success', 'warning', 'info'] as const;
</script>

<div class="max-w-[800px] mx-auto p-6 space-y-6">
  <header>
    <h1 class="text-[24px] font-bold">Design Engine Settings</h1>
    <p class="text-[14px] text-text-secondary">
      Tweak design tokens. Edits produce a copyable CSS snippet — paste into theme.css to apply.
    </p>
  </header>

  <div class="bg-card p-6 rounded-2xl space-y-3">
    <h2 class="text-[18px] font-bold">Colors</h2>
    {#each colorKeys as key}
      <div class="flex items-center gap-4">
        <label class="w-32 text-[14px] font-mono">--{key}</label>
        <input type="color" bind:value={tokens[key]} class="w-16 h-10" />
        <input type="text" bind:value={tokens[key]} class="font-mono p-2 border rounded-md" />
      </div>
    {/each}
  </div>

  <div class="bg-card p-6 rounded-2xl">
    <h2 class="text-[18px] font-bold mb-4">Font</h2>
    <select bind:value={tokens.font} class="w-full p-2 border rounded-md">
      <option>Inter</option>
      <option>Pretendard</option>
      <option>Geist</option>
      <option>DM Sans</option>
      <option>System default</option>
    </select>
  </div>

  <div class="bg-card p-6 rounded-2xl">
    <h2 class="text-[18px] font-bold mb-4">Live Preview</h2>
    <div class="p-4 rounded-2xl shadow-[var(--shadow-card)]" style="background: {tokens.card}; color: {tokens.foreground}; font-family: {tokens.font}">
      <p class="text-[12px] uppercase tracking-wide font-bold">SAMPLE CARD</p>
      <p class="text-[36px] font-bold">$48.2<span class="text-[18px]">K</span></p>
      <p class="text-[13px] font-bold" style="color: {tokens.success}">+8.2% vs last month</p>
      <button class="mt-4 px-4 py-2 rounded-md text-white font-medium" style="background: {tokens.brand}">
        Primary Action
      </button>
    </div>
  </div>

  <div class="bg-card p-6 rounded-2xl space-y-4">
    <h2 class="text-[18px] font-bold">Generated CSS</h2>
    <pre class="bg-[#FAFAFA] p-4 rounded-md overflow-x-auto text-[13px]">{cssOutput}</pre>
    <div class="flex gap-2">
      <button onclick={copyCss} class="px-4 py-2 bg-primary text-white rounded-md">Copy CSS</button>
      <button onclick={downloadCss} class="px-4 py-2 border rounded-md">Download theme.css</button>
    </div>
  </div>
</div>
