<script lang="ts">
  // Generated by design-engine /design-settings-page
  // Adapter: sveltekit (direct write-back mode)
  //
  // Loads tokens from /__design/api/tokens and writes them back live.
  // The dev gate lives in the +server.ts handler — in production the API
  // returns 404, so the page renders an error state. For an extra fail-safe,
  // co-locate a +page.ts with `if (!dev) error(404);`.

  import { onMount } from 'svelte';
  import { browser } from '$app/environment';

  type TokenValue = { $value: string };
  type TokenGroup = { $type?: string; [name: string]: TokenValue | string | undefined };
  type Tokens = { [group: string]: TokenGroup };
  type FontEntry = { family: string; category: string; weights?: number[]; axisRange?: string };

  const GROUP_TO_PREFIX: Record<string, string> = {
    color: '', radius: 'radius', font: 'font',
    shadow: 'shadow', spacing: 'spacing', motion: 'duration',
  };
  const COLOR_RE = /^#(?:[0-9a-f]{3,8})$/i;
  const COLOR_FUNC_RE = /^(?:oklch|oklab|hsl|hsla|rgb|rgba)\s*\(/i;

  function tokenKeyToCssName(group: string, key: string): string {
    const prefix = GROUP_TO_PREFIX[group];
    if (prefix === undefined) return key;
    if (prefix === '') return key;
    if (key === 'default') return prefix;
    return `${prefix}-${key}`;
  }

  function isColorValue(value: string): boolean {
    return COLOR_RE.test(value) || COLOR_FUNC_RE.test(value);
  }

  function getFontFamily(t: Tokens | null): string {
    if (!t?.font) return 'Inter';
    for (const [key, val] of Object.entries(t.font)) {
      if (key === '$type') continue;
      if (val && typeof val === 'object' && '$value' in val) {
        return val.$value.split(',')[0].trim().replace(/^['"]|['"]$/g, '');
      }
    }
    return 'Inter';
  }

  const OFFLINE_FONTS: FontEntry[] = [
    { family: 'Inter', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
    { family: 'Geist', category: 'sans-serif', weights: [400, 500, 600, 700] },
    { family: 'Pretendard', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
    { family: 'DM Sans', category: 'sans-serif', weights: [400, 500, 700] },
    { family: 'Manrope', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
    { family: 'Plus Jakarta Sans', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
    { family: 'IBM Plex Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
    { family: 'Roboto', category: 'sans-serif', weights: [400, 500, 700] },
    { family: 'Open Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
    { family: 'Source Sans 3', category: 'sans-serif', weights: [400, 600, 700] },
    { family: 'JetBrains Mono', category: 'monospace', weights: [400, 500, 700] },
    { family: 'Space Grotesk', category: 'sans-serif', weights: [400, 500, 700] },
    { family: 'Outfit', category: 'sans-serif', weights: [400, 500, 600, 700] },
    { family: 'Albert Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
  ];

  // Same-origin proxy installed by src/routes/__design/api/google-fonts/+server.ts.
  // The browser-side fetch must NOT hit fonts.google.com directly — that endpoint
  // is same-origin only and CORS-blocks browser fetches.
  const GOOGLE_FONTS_PROXY_URL = '/__design/api/google-fonts';
  const CATALOG_CACHE_KEY = 'de-google-fonts-catalog-v2';

  let tokens = $state<Tokens | null>(null);
  let loadError = $state<string | null>(null);
  let saveError = $state<string | null>(null);
  let statusKind = $state<'idle' | 'saving' | 'saved'>('idle');
  let fontInput = $state<string>('');
  let suggestionsOpen = $state<boolean>(false);
  let fontEntries = $state<FontEntry[]>(OFFLINE_FONTS);

  let saveTimer: ReturnType<typeof setTimeout> | null = null;
  let savedHideTimer: ReturnType<typeof setTimeout> | null = null;
  let suggestionsHideTimer: ReturnType<typeof setTimeout> | null = null;
  let catalogPromise: Promise<FontEntry[]> | null = null;
  let catalogState = $state<'idle' | 'loading' | 'ready' | 'failed'>('idle');

  const filteredFonts = $derived(
    fontEntries.filter((f) => f.family.toLowerCase().includes(fontInput.toLowerCase())).slice(0, 20),
  );

  const cssOutput = $derived(generateCss(tokens));

  function generateCss(t: Tokens | null): string {
    if (!t) return '';
    const lines: string[] = [];
    for (const [group, groupObj] of Object.entries(t)) {
      for (const [key, val] of Object.entries(groupObj)) {
        if (key === '$type') continue;
        if (!val || typeof val === 'string') continue;
        const cssName = tokenKeyToCssName(group, key);
        lines.push(`  --${cssName}: ${val.$value};`);
      }
    }
    return `:root {\n${lines.join('\n')}\n}`;
  }

  function styleVars(t: Tokens): string {
    const vars: string[] = [];
    for (const [group, groupObj] of Object.entries(t)) {
      for (const [key, val] of Object.entries(groupObj)) {
        if (key === '$type') continue;
        if (!val || typeof val !== 'object' || !('$value' in val)) continue;
        const cssName = tokenKeyToCssName(group, key);
        vars.push(`--de-${cssName}: ${val.$value}`);
      }
    }
    const fontFamily = getFontFamily(t);
    vars.push(`--de-font-primary: '${fontFamily}', system-ui, sans-serif`);
    return vars.join('; ');
  }

  onMount(() => {
    void bootstrap();
    return () => {
      if (saveTimer !== null) clearTimeout(saveTimer);
      if (savedHideTimer !== null) clearTimeout(savedHideTimer);
      if (suggestionsHideTimer !== null) clearTimeout(suggestionsHideTimer);
    };
  });

  async function bootstrap() {
    try {
      const res = await fetch('/__design/api/tokens');
      if (!res.ok) {
        const body = await res.json().catch(() => ({ message: res.statusText }));
        throw new Error(body.message ?? 'Failed to load tokens');
      }
      tokens = await res.json();
      fontInput = getFontFamily(tokens);
    } catch (e) {
      loadError = String((e as Error).message);
    }
  }

  function scheduleSave() {
    if (saveTimer !== null) clearTimeout(saveTimer);
    saveTimer = setTimeout(() => { void flushSave(); }, 500);
  }

  async function flushSave() {
    if (!tokens) return;
    if (saveTimer !== null) { clearTimeout(saveTimer); saveTimer = null; }
    statusKind = 'saving';
    try {
      const res = await fetch('/__design/api/tokens', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify($state.snapshot(tokens)),
      });
      const body = await res.json();
      if (body.tokens) tokens = body.tokens;
      if (!res.ok || !body.ok) throw new Error(body.message ?? `HTTP ${res.status}`);
      saveError = null;
      statusKind = 'saved';
      if (savedHideTimer !== null) clearTimeout(savedHideTimer);
      savedHideTimer = setTimeout(() => {
        if (statusKind === 'saved') statusKind = 'idle';
      }, 1500);
    } catch (e) {
      saveError = String((e as Error).message);
      statusKind = 'idle';
    }
  }

  function onTokenChange(group: string, key: string, value: string) {
    if (!tokens || !tokens[group]) return;
    (tokens[group][key] as TokenValue) = { $value: value };
    scheduleSave();
  }

  function onFontInput(v: string) {
    fontInput = v;
    suggestionsOpen = true;
  }

  function onFontPick(f: FontEntry) {
    if (!tokens) return;
    fontInput = f.family;
    updateFontToken(f.family);
    suggestionsOpen = false;
    void flushSave();
  }

  function updateFontToken(name: string) {
    if (!tokens) return;
    if (!tokens.font) tokens.font = { $type: 'fontFamily' };
    const formatted = `'${name}', system-ui, -apple-system, BlinkMacSystemFont, sans-serif`;
    const firstKey = Object.keys(tokens.font).find(k => k !== '$type');
    if (firstKey) {
      (tokens.font[firstKey] as TokenValue) = { $value: formatted };
    } else {
      (tokens.font as any).primary = { $value: formatted };
    }
  }

  function onFontFocus() {
    suggestionsOpen = true;
    if (browser) void ensureCatalog();
  }

  async function ensureCatalog() {
    if (catalogState === 'ready' || catalogState === 'failed' || catalogState === 'loading') return;
    catalogState = 'loading';
    try {
      await loadGoogleFontsCatalog();
      catalogState = 'ready';
    } catch {
      catalogState = 'failed';
    }
  }

  function onFontBlur() {
    if (!tokens) return;
    updateFontToken(fontInput);
    if (suggestionsHideTimer !== null) clearTimeout(suggestionsHideTimer);
    suggestionsHideTimer = setTimeout(() => { suggestionsOpen = false; }, 150);
    void flushSave();
  }

  async function loadGoogleFontsCatalog(): Promise<FontEntry[]> {
    if (catalogPromise) return catalogPromise;

    try {
      const cached = sessionStorage.getItem(CATALOG_CACHE_KEY);
      if (cached) {
        const parsed = JSON.parse(cached) as FontEntry[];
        if (Array.isArray(parsed) && parsed.length > 0) {
          fontEntries = parsed;
          catalogState = 'ready';
          return parsed;
        }
      }
    } catch { /* corrupt cache — refetch */ }

    catalogPromise = (async () => {
      const res = await fetch(GOOGLE_FONTS_PROXY_URL);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (!Array.isArray(data) || data.length === 0) throw new Error('Empty catalog');
      try { sessionStorage.setItem(CATALOG_CACHE_KEY, JSON.stringify(data)); } catch { /* quota — skip cache */ }
      fontEntries = data;
      return data as FontEntry[];
    })();
    return catalogPromise;
  }

  function copyCss() {
    if (!browser) return;
    void navigator.clipboard.writeText(cssOutput);
  }

  function retrySave() {
    saveError = null;
    void flushSave();
  }
</script>

<svelte:head>
  <title>Design Engine Settings</title>
</svelte:head>

{#if loadError}
  <div class="de-page">
    <h1 class="de-title">Design Engine Settings</h1>
    <div class="de-error-box">
      <p><strong>Could not load tokens.json</strong></p>
      <p>{loadError}</p>
    </div>
  </div>
{:else if !tokens}
  <div class="de-loading">Loading…</div>
{:else}
  <div class="de-page-root" style={styleVars(tokens)}>
    <div class="de-page">
      <header class="de-header">
        <div>
          <h1 class="de-title">Design Engine Settings</h1>
          <p class="de-subtitle">Edit tokens — changes save and reload automatically.</p>
        </div>
        <div class="de-header-right">
          {#if statusKind === 'saving'}
            <span class="de-status de-status-saving">Saving…</span>
          {:else if statusKind === 'saved'}
            <span class="de-status de-status-saved">Saved</span>
          {/if}
          {#if saveError}
            <span class="de-status de-status-error">
              Error: {saveError}
              <button type="button" class="de-retry" onclick={retrySave}>Retry</button>
            </span>
          {/if}
        </div>
      </header>

      {#each Object.entries(tokens) as [group, groupObj]}
        <div class="de-card">
          <h2>{group.charAt(0).toUpperCase() + group.slice(1)}</h2>
          {#each Object.entries(groupObj) as [key, val]}
            {#if key !== '$type' && val && typeof val === 'object' && '$value' in val}
              {@const cssName = tokenKeyToCssName(group, key)}
              {@const isColor = groupObj.$type === 'color' || isColorValue(val.$value)}
              <div class="de-color-row">
                <label>--{cssName}</label>
                {#if isColor}
                  <input
                    type="color"
                    value={val.$value}
                    oninput={(e) => onTokenChange(group, key, e.currentTarget.value)}
                    onblur={() => void flushSave()}
                  />
                {/if}
                <input
                  type="text"
                  value={val.$value}
                  style={isColor ? '' : 'flex: 1'}
                  oninput={(e) => onTokenChange(group, key, e.currentTarget.value)}
                  onblur={() => void flushSave()}
                />
              </div>
            {/if}
          {/each}
        </div>
      {/each}

      <div class="de-card">
        <h2>Font</h2>
        <div class="de-relative">
          <input
            type="text"
            class="de-font-input"
            placeholder="Type a font name…"
            autocomplete="off"
            value={fontInput}
            oninput={(e) => onFontInput(e.currentTarget.value)}
            onfocus={onFontFocus}
            onblur={onFontBlur}
          />
          {#if suggestionsOpen && (filteredFonts.length > 0 || catalogState === 'loading' || catalogState === 'failed')}
            <div class="de-font-suggestions">
              {#if catalogState === 'loading'}
                <div class="de-font-hint">Loading Google Fonts catalog…</div>
              {:else if catalogState === 'failed'}
                <div class="de-font-hint">Couldn’t load the full Google Fonts catalog. Showing common fonts only.</div>
              {/if}
              {#each filteredFonts as f (f.family)}
                <button type="button" onmousedown={(e) => { e.preventDefault(); onFontPick(f); }}>
                  <span style="font-family: '{f.family}', system-ui">{f.family}</span>
                  <span class="de-font-cat">{f.category}</span>
                </button>
              {/each}
            </div>
          {/if}
        </div>
      </div>

      <div class="de-card">
        <h2>Live Preview</h2>
        <div class="de-demo">
          <section>
            <h1 class="de-demo-h1">Display heading</h1>
            <h2 class="de-demo-h2">Section heading</h2>
            <p class="de-demo-p">Body paragraph showing how foreground color and the primary font interact at default reading size.</p>
            <p class="de-demo-small">Small label / muted text</p>
            <code class="de-demo-code">inline code</code>
          </section>

          <div class="de-demo-row">
            <button type="button" class="de-btn de-btn-brand">Brand</button>
            <button type="button" class="de-btn de-btn-primary">Primary</button>
            <button type="button" class="de-btn de-btn-destructive">Destructive</button>
            <button type="button" class="de-btn de-btn-outline">Outline</button>
          </div>

          <div class="de-demo-row">
            <span class="de-chip de-chip-success">Success</span>
            <span class="de-chip de-chip-warning">Warning</span>
            <span class="de-chip de-chip-error">Error</span>
            <span class="de-chip de-chip-info">Info</span>
          </div>

          <div class="de-form">
            <input type="text" placeholder="Text input" />
            <select>
              <option>Option A</option>
              <option>Option B</option>
            </select>
          </div>

          <div class="de-stat-card">
            <p class="de-stat-label">REVENUE</p>
            <p class="de-stat-value">$48.2K</p>
            <p class="de-stat-delta">+8.2% vs last month</p>
          </div>
        </div>
      </div>

      <div class="de-card">
        <h2>Generated CSS (fallback)</h2>
        <p class="de-note">Live write-back is active. Use this snippet for sharing or as a fallback.</p>
        <pre class="de-pre">{cssOutput}</pre>
        <button type="button" class="de-btn de-btn-outline de-copy" onclick={copyCss}>Copy CSS</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .de-page-root {
    background: var(--de-background);
    color: var(--de-foreground);
    font-family: var(--de-font-primary);
    min-height: 100vh;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  .de-page {
    max-width: 900px;
    margin: 0 auto;
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 24px;
  }
  .de-loading {
    padding: 24px;
    font-size: 14px;
  }
  .de-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 12px;
  }
  .de-header-right {
    display: flex;
    align-items: center;
    gap: 12px;
  }
  .de-title {
    font-size: 24px;
    font-weight: 700;
    margin: 0;
  }
  .de-subtitle {
    font-size: 14px;
    opacity: 0.7;
    margin: 4px 0 0 0;
  }
  .de-status {
    font-size: 12px;
  }
  .de-status-saving { opacity: 0.7; }
  .de-status-saved { color: var(--de-success); }
  .de-status-error { color: var(--de-destructive); }
  .de-retry {
    margin-left: 8px;
    background: transparent;
    color: inherit;
    border: 1px solid currentColor;
    border-radius: 4px;
    padding: 2px 8px;
    cursor: pointer;
    font: inherit;
  }
  .de-card {
    background: var(--de-card);
    border: 1px solid color-mix(in oklab, var(--de-foreground) 10%, transparent);
    border-radius: 8px;
    padding: 24px;
  }
  .de-card h2 {
    font-size: 18px;
    font-weight: 700;
    margin: 0 0 16px 0;
  }
  .de-color-row {
    display: flex;
    align-items: center;
    gap: 16px;
    margin-bottom: 12px;
  }
  .de-color-row label {
    width: 128px;
    font-family: ui-monospace, monospace;
    font-size: 13px;
  }
  .de-color-row input[type='color'] {
    width: 64px;
    height: 40px;
    border: none;
    padding: 0;
    background: transparent;
    cursor: pointer;
  }
  .de-color-row input[type='text'] {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid color-mix(in oklab, var(--de-foreground) 20%, transparent);
    border-radius: 6px;
    font-family: ui-monospace, monospace;
    background: var(--de-background);
    color: var(--de-foreground);
  }
  .de-relative { position: relative; }
  .de-font-input {
    width: 100%;
    padding: 8px 12px;
    border: 1px solid color-mix(in oklab, var(--de-foreground) 20%, transparent);
    border-radius: 6px;
    font-family: ui-monospace, monospace;
    background: var(--de-background);
    color: var(--de-foreground);
    box-sizing: border-box;
  }
  .de-font-suggestions {
    position: absolute;
    z-index: 10;
    background: var(--de-card);
    border: 1px solid color-mix(in oklab, var(--de-foreground) 20%, transparent);
    border-radius: 6px;
    max-height: 256px;
    overflow-y: auto;
    left: 0;
    right: 0;
    top: 100%;
    margin-top: 4px;
  }
  .de-font-suggestions button {
    display: flex;
    justify-content: space-between;
    width: 100%;
    padding: 8px 12px;
    background: transparent;
    border: none;
    cursor: pointer;
    color: inherit;
    text-align: left;
  }
  .de-font-suggestions button:hover {
    background: color-mix(in oklab, var(--de-foreground) 5%, transparent);
  }
  .de-font-cat {
    font-size: 11px;
    opacity: 0.6;
  }
  .de-font-hint {
    font-size: 11px;
    opacity: 0.6;
    padding: 8px 12px;
  }
  .de-demo {
    display: flex;
    flex-direction: column;
    gap: 24px;
  }
  .de-demo-h1 {
    font-size: 32px;
    font-weight: 700;
    margin: 0;
  }
  .de-demo-h2 {
    font-size: 20px;
    font-weight: 600;
    margin: 8px 0;
  }
  .de-demo-p {
    font-size: 14px;
    margin: 8px 0;
  }
  .de-demo-small {
    font-size: 12px;
    opacity: 0.7;
    margin: 8px 0;
  }
  .de-demo-code {
    font-size: 12px;
    padding: 2px 6px;
    background: color-mix(in oklab, var(--de-foreground) 10%, transparent);
    border-radius: 4px;
    font-family: ui-monospace, monospace;
  }
  .de-demo-row {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .de-btn {
    padding: 6px 12px;
    border-radius: 6px;
    font-size: 13px;
    border: none;
    cursor: pointer;
    color: white;
    font: inherit;
    font-weight: 500;
  }
  .de-btn-brand { background: var(--de-brand); }
  .de-btn-primary { background: var(--de-primary); }
  .de-btn-destructive { background: var(--de-destructive); }
  .de-btn-outline {
    background: transparent;
    color: var(--de-foreground);
    border: 1px solid color-mix(in oklab, var(--de-foreground) 30%, transparent);
  }
  .de-chip {
    padding: 2px 8px;
    border-radius: 4px;
    font-size: 12px;
    color: white;
  }
  .de-chip-success { background: var(--de-success); }
  .de-chip-warning { background: var(--de-warning); }
  .de-chip-error { background: var(--de-destructive); }
  .de-chip-info { background: var(--de-info); }
  .de-form {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    max-width: 480px;
  }
  .de-form input,
  .de-form select {
    padding: 8px 12px;
    border: 1px solid color-mix(in oklab, var(--de-foreground) 20%, transparent);
    border-radius: 6px;
    background: var(--de-background);
    color: var(--de-foreground);
    font-size: 14px;
  }
  .de-stat-card {
    background: var(--de-card);
    border: 1px solid color-mix(in oklab, var(--de-foreground) 10%, transparent);
    border-radius: 8px;
    padding: 16px;
    max-width: 320px;
  }
  .de-stat-label {
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    font-weight: 700;
    opacity: 0.7;
    margin: 0;
  }
  .de-stat-value {
    font-size: 36px;
    font-weight: 700;
    margin: 4px 0;
  }
  .de-stat-delta {
    font-size: 13px;
    font-weight: 700;
    color: var(--de-success);
    margin: 0;
  }
  .de-note {
    font-size: 12px;
    opacity: 0.7;
    margin: 0 0 12px 0;
  }
  .de-pre {
    background: color-mix(in oklab, var(--de-foreground) 5%, transparent);
    padding: 16px;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 12px;
    font-family: ui-monospace, monospace;
    white-space: pre;
    margin: 0;
  }
  .de-copy {
    margin-top: 12px;
  }
  .de-error-box {
    background: var(--de-card, #fff);
    border: 1px solid var(--de-destructive, #d4183d);
    border-radius: 8px;
    padding: 24px;
    color: var(--de-destructive, #d4183d);
  }
</style>
