// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Helper: parses and writes theme.css surgically; manages fonts.css @import block.
// Server-side only (Node fs). Never imported from client code.

import { readFile, writeFile, rename } from 'node:fs/promises';

export const MANAGED_COLOR_KEYS = [
  'brand', 'primary', 'background', 'card', 'foreground',
  'destructive', 'success', 'warning', 'info'
] as const;

export type ColorKey = typeof MANAGED_COLOR_KEYS[number];
export type Mode = 'light' | 'dark';
export type ColorTokens = { [K in ColorKey]: string };
export type TokenSet = {
  light: ColorTokens;
  dark: ColorTokens;
  font: string;
};

export type ParseError = 'no_root_block' | 'ambiguous_root' | 'ambiguous_dark' | 'duplicate_decl' | 'read_failed';
export type WriteError = ParseError | 'no_dark_block' | 'write_failed';
export type ParseResult = { ok: true; tokens: TokenSet } | { ok: false; error: ParseError; message: string };
export type WriteResult = { ok: true; tokens: TokenSet } | { ok: false; error: WriteError; message: string };

const MANAGED_VAR_NAMES = [...MANAGED_COLOR_KEYS, 'font-primary'] as const;
const FALLBACK_COLORS: ColorTokens = {
  brand: '#721FE5', primary: '#030213', background: '#FAFAFA', card: '#FFFFFF',
  foreground: '#2A2A2A', destructive: '#d4183d', success: '#6B9B7A',
  warning: '#D97706', info: '#3B82F6',
};
const FALLBACK_FONT = 'Inter';

export async function readTokens(themePath: string): Promise<ParseResult> {
  let raw: string;
  try { raw = await readFile(themePath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }
  return parseTokens(raw);
}

export function parseTokens(css: string): ParseResult {
  const blocks = scanTopLevelBlocks(css);
  const rootBlocks = blocks.filter(b => b.selector === ':root' && blockContainsManagedToken(css, b));
  const darkBlocks = blocks.filter(b => b.selector === '.dark' && blockContainsManagedToken(css, b));

  if (rootBlocks.length === 0) return { ok: false, error: 'no_root_block', message: 'No top-level :root block contains managed tokens.' };
  if (rootBlocks.length > 1) return { ok: false, error: 'ambiguous_root', message: `Multiple top-level :root blocks contain managed tokens (${rootBlocks.length}).` };
  if (darkBlocks.length > 1) return { ok: false, error: 'ambiguous_dark', message: `Multiple top-level .dark blocks contain managed tokens (${darkBlocks.length}).` };

  const lightBody = css.slice(rootBlocks[0].bodyStart, rootBlocks[0].bodyEnd);
  const lightDecls = scanDeclarations(lightBody);
  if (hasDuplicates(lightDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in :root block.' };

  const lightColors: ColorTokens = { ...FALLBACK_COLORS };
  let font = FALLBACK_FONT;
  for (const d of lightDecls) {
    if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (lightColors as any)[d.name] = d.value;
    else if (d.name === 'font-primary') font = parseFontPrimary(d.value);
  }

  let darkColors: ColorTokens = { ...lightColors };
  if (darkBlocks.length === 1) {
    const darkBody = css.slice(darkBlocks[0].bodyStart, darkBlocks[0].bodyEnd);
    const darkDecls = scanDeclarations(darkBody);
    if (hasDuplicates(darkDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in .dark block.' };
    for (const d of darkDecls) {
      if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (darkColors as any)[d.name] = d.value;
    }
  }

  return { ok: true, tokens: { light: lightColors, dark: darkColors, font } };
}

export type Block = { selector: ':root' | '.dark'; headerStart: number; bodyStart: number; bodyEnd: number };

export function scanTopLevelBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  let i = 0;
  let depth = 0;

  while (i < css.length) {
    const c = css[i];

    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }

    if (c === '{') { depth++; i++; continue; }
    if (c === '}') { depth--; i++; continue; }

    if (depth === 0) {
      const remaining = css.slice(i);
      const rootMatch = remaining.match(/^:root(?=\s*\{)/);
      const darkMatch = remaining.match(/^\.dark(?=\s*\{)/);
      const match = rootMatch ?? darkMatch;
      if (match) {
        const headerStart = i;
        const openIdx = css.indexOf('{', i);
        if (openIdx === -1) break;
        const closeIdx = findMatchingBrace(css, openIdx);
        if (closeIdx === -1) break;
        blocks.push({
          selector: rootMatch ? ':root' : '.dark',
          headerStart,
          bodyStart: openIdx + 1,
          bodyEnd: closeIdx,
        });
        i = closeIdx + 1;
        continue;
      }
    }

    i++;
  }
  return blocks;
}

function findMatchingBrace(css: string, openIdx: number): number {
  let depth = 1;
  let i = openIdx + 1;
  while (i < css.length) {
    const c = css[i];
    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return i;
    }
    i++;
  }
  return -1;
}

export type Declaration = {
  name: string;
  value: string;
  valueStart: number;
  valueEnd: number;
};

export function scanDeclarations(body: string): Declaration[] {
  const decls: Declaration[] = [];
  let i = 0;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    // Skip strings — declaration values like `content: "--brand: #fff"` must not register as managed declarations.
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '-' && body[i + 1] === '-') {
      const decl = parseDeclarationAt(body, i);
      if (decl && (MANAGED_VAR_NAMES as readonly string[]).includes(decl.name)) {
        decls.push(decl);
        i = decl.valueEnd + 1;
        continue;
      }
    }
    i++;
  }
  return decls;
}

function parseDeclarationAt(body: string, start: number): Declaration | null {
  const colonIdx = findColonSkippingCommentsAndStrings(body, start);
  if (colonIdx === -1) return null;
  const name = body.slice(start + 2, colonIdx).trim();
  if (!/^[a-z][a-z0-9-]*$/i.test(name)) return null;
  let valueStart = colonIdx + 1;
  while (valueStart < body.length && /\s/.test(body[valueStart])) valueStart++;
  const semiIdx = findSemicolonSkippingStrings(body, valueStart);
  if (semiIdx === -1) return null;
  const value = body.slice(valueStart, semiIdx).trim();
  return { name, value, valueStart, valueEnd: semiIdx };
}

function findColonSkippingCommentsAndStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ':') return i;
    if (c === ';' || c === '{' || c === '}' || c === '\n') return -1;
    i++;
  }
  return -1;
}

function findSemicolonSkippingStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ';' || c === '}') return c === ';' ? i : -1;
    i++;
  }
  return -1;
}

function blockContainsManagedToken(css: string, block: Block): boolean {
  const body = css.slice(block.bodyStart, block.bodyEnd);
  return scanDeclarations(body).length > 0;
}

function hasDuplicates(decls: Declaration[]): boolean {
  const seen = new Set<string>();
  for (const d of decls) {
    if (seen.has(d.name)) return true;
    seen.add(d.name);
  }
  return false;
}

function parseFontPrimary(raw: string): string {
  const first = raw.split(',')[0].trim();
  return first.replace(/^['"]|['"]$/g, '');
}

async function atomicWrite(filePath: string, contents: string): Promise<void> {
  const tmp = filePath + '.tmp';
  await writeFile(tmp, contents, 'utf8');
  let lastErr: unknown;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      await rename(tmp, filePath);
      return;
    } catch (e: any) {
      lastErr = e;
      if (e?.code !== 'EBUSY' && e?.code !== 'EPERM' && e?.code !== 'EACCES') throw e;
      await new Promise(r => setTimeout(r, 50));
    }
  }
  throw lastErr;
}

export async function writeTokens(themePath: string, mode: Mode, colors: ColorTokens, font?: string): Promise<WriteResult> {
  let raw: string;
  try { raw = await readFile(themePath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }

  const blocks = scanTopLevelBlocks(raw);
  const targetSelector = mode === 'light' ? ':root' : '.dark';
  const targets = blocks.filter(b => b.selector === targetSelector && blockContainsManagedToken(raw, b));

  if (targets.length === 0) return { ok: false, error: mode === 'light' ? 'no_root_block' : 'no_dark_block', message: `No ${targetSelector} block with managed tokens.` };
  if (targets.length > 1) return { ok: false, error: mode === 'light' ? 'ambiguous_root' : 'ambiguous_dark', message: `Multiple ${targetSelector} blocks with managed tokens.` };

  const block = targets[0];
  const bodyStart = block.bodyStart;
  const bodyEnd = block.bodyEnd;
  const body = raw.slice(bodyStart, bodyEnd);
  const decls = scanDeclarations(body);
  if (hasDuplicates(decls)) {
    return { ok: false, error: 'duplicate_decl', message: `Duplicate managed variable in ${targetSelector} block.` };
  }

  const wantedReplacements = new Map<string, string>();
  for (const k of MANAGED_COLOR_KEYS) wantedReplacements.set(k, colors[k]);
  if (mode === 'light' && font !== undefined) wantedReplacements.set('font-primary', formatFontPrimary(font));

  const allKeys: readonly string[] = mode === 'light' ? [...MANAGED_COLOR_KEYS, 'font-primary'] : MANAGED_COLOR_KEYS;

  let newBody = body;
  const orderedExisting = decls
    .filter(d => wantedReplacements.has(d.name))
    .sort((a, b) => b.valueStart - a.valueStart);
  for (const d of orderedExisting) {
    const newValue = wantedReplacements.get(d.name)!;
    newBody = newBody.slice(0, d.valueStart) + newValue + newBody.slice(d.valueEnd);
    wantedReplacements.delete(d.name);
  }

  if (wantedReplacements.size > 0) {
    const trailingMatch = newBody.match(/(\s*)$/);
    const trailing = trailingMatch?.[1] ?? '';
    const insertAt = newBody.length - trailing.length;
    const missing = Array.from(wantedReplacements.entries())
      .filter(([k]) => allKeys.includes(k))
      .map(([k, v]) => `\n  --${k}: ${v};`)
      .join('');
    newBody = newBody.slice(0, insertAt) + missing + newBody.slice(insertAt);
  }

  const newRaw = raw.slice(0, bodyStart) + newBody + raw.slice(bodyEnd);

  try { await atomicWrite(themePath, newRaw); }
  catch (e) { return { ok: false, error: 'write_failed', message: String(e) }; }

  const reread = await readTokens(themePath);
  if (!reread.ok) return { ok: false, error: 'write_failed', message: 'Wrote file but failed to re-read: ' + reread.message };
  return { ok: true, tokens: reread.tokens };
}

function formatFontPrimary(name: string): string {
  const needsQuotes = /[^a-zA-Z0-9-]/.test(name);
  const quoted = needsQuotes ? `'${name}'` : name;
  return `${quoted}, system-ui, -apple-system, BlinkMacSystemFont, sans-serif`;
}

export type FontImportEntry = {
  name: string;
  url: string;
};

const FONT_BLOCK_START = '/* design-engine: managed-font-imports:start */';
const FONT_BLOCK_END = '/* design-engine: managed-font-imports:end */';

export type FontImportResult = { ok: true } | { ok: false; error: string; message: string };

export async function writeFontImports(fontsPath: string, entries: FontImportEntry[]): Promise<FontImportResult> {
  let raw: string;
  try { raw = await readFile(fontsPath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }

  const newBlock = renderFontImportBlock(entries);
  const startIdx = raw.indexOf(FONT_BLOCK_START);
  const endIdx = raw.indexOf(FONT_BLOCK_END);

  let newRaw: string;
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const blockEnd = endIdx + FONT_BLOCK_END.length;
    newRaw = raw.slice(0, startIdx) + newBlock + raw.slice(blockEnd);
  } else {
    newRaw = newBlock + '\n\n' + raw;
  }

  try { await atomicWrite(fontsPath, newRaw); }
  catch (e) { return { ok: false, error: 'write_failed', message: String(e) }; }
  return { ok: true };
}

function renderFontImportBlock(entries: FontImportEntry[]): string {
  const lines = entries.map(e => `@import url('${e.url}');`).join('\n');
  return `${FONT_BLOCK_START}\n${lines}${lines ? '\n' : ''}${FONT_BLOCK_END}`;
}

export function buildGoogleFontsUrl(family: string, weights?: number[], axisRange?: string): string {
  const familyParam = family.replace(/ /g, '+');
  let suffix = '';
  if (axisRange) suffix = `:wght@${axisRange}`;
  else if (weights && weights.length) suffix = `:wght@${weights.join(';')}`;
  return `https://fonts.googleapis.com/css2?family=${familyParam}${suffix}&display=swap`;
}

// ---------------------------------------------------------------------------
// W3C Design Tokens bridge: read CSS vars into grouped token structure,
// write grouped tokens back to flat CSS vars.
// Complements (does not replace) parseTokens / writeTokens above.
// ---------------------------------------------------------------------------

export type TokenValue = { $value: string };
export type TokenGroup = {
  $type?: string;
  [name: string]: TokenValue | string | undefined;
};
export type Tokens = {
  [group: string]: TokenGroup;
};

// Patterns for detecting value types
const COLOR_HEX_RE = /^#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;
const COLOR_FUNC_RE = /^(?:oklch|oklab|hsl|hsla|rgb|rgba)\s*\(/i;
const DIMENSION_RE = /^-?[\d.]+(?:px|rem|em|%)$/;
const FONT_FAMILY_RE = /['"]/; // contains quotes -> likely font family
const FONT_COMMA_RE = /,/;     // comma-separated -> likely font stack

// Name-prefix grouping rules (order matters: more specific first)
const PREFIX_GROUPS: Array<{ prefix: string; group: string }> = [
  { prefix: 'font-', group: 'font' },
  { prefix: 'radius-', group: 'radius' },
  { prefix: 'shadow-', group: 'shadow' },
  { prefix: 'spacing-', group: 'spacing' },
  { prefix: 'duration-', group: 'motion' },
];

// Exact-match name -> group (for bare names like --radius with no suffix)
const EXACT_GROUPS: Record<string, { group: string; key: string }> = {
  'radius': { group: 'radius', key: 'default' },
};

function detectValueType(value: string): string {
  if (COLOR_HEX_RE.test(value)) return 'color';
  if (COLOR_FUNC_RE.test(value)) return 'color';
  if (DIMENSION_RE.test(value)) return 'dimension';
  if (FONT_FAMILY_RE.test(value) || FONT_COMMA_RE.test(value)) return 'fontFamily';
  return 'other';
}

function classifyVar(name: string, value: string): { group: string; key: string; type: string } {
  // Check exact name matches first (e.g., --radius -> radius.default)
  const exact = EXACT_GROUPS[name];
  if (exact) {
    return { group: exact.group, key: exact.key, type: 'dimension' };
  }

  // Check prefix-based groups
  for (const { prefix, group } of PREFIX_GROUPS) {
    if (name.startsWith(prefix)) {
      const suffix = name.slice(prefix.length);
      const type = group === 'font' ? 'fontFamily' : group === 'motion' ? 'duration' : 'dimension';
      return { group, key: suffix, type };
    }
  }

  // Fall back to value-based type detection
  const type = detectValueType(value);
  if (type === 'color') return { group: 'color', key: name, type: 'color' };
  if (type === 'fontFamily') return { group: 'font', key: name, type: 'fontFamily' };
  if (type === 'dimension') return { group: 'dimension', key: name, type: 'dimension' };
  return { group: 'other', key: name, type };
}

/**
 * Extract all --name: value pairs from CSS blocks (:root, .dark,
 * @theme, @theme inline), detect each value's type, and return a W3C-style
 * grouped token object.
 *
 * Only reads :root (light) tokens currently. Dark-mode grouping can be
 * added later by returning a { light: Tokens; dark: Tokens } wrapper.
 */
export function readTokensFromCss(css: string): Tokens {
  const tokens: Tokens = {};

  // Extract var declarations from supported blocks
  const pairs = extractAllVarDeclarations(css);

  for (const { name, value } of pairs) {
    const { group, key, type } = classifyVar(name, value);

    if (!tokens[group]) {
      tokens[group] = { $type: type };
    }
    (tokens[group] as any)[key] = { $value: value };
  }

  return tokens;
}

/** Regex-extract --name: value pairs from :root, .dark, @theme blocks. */
function extractAllVarDeclarations(css: string): Array<{ name: string; value: string }> {
  const pairs: Array<{ name: string; value: string }> = [];

  // Find all block bodies we care about: :root, .dark, @theme, @theme inline
  const blockRe = /(?::root|\.dark|@theme(?:\s+inline)?)\s*\{/g;
  let match: RegExpExecArray | null;

  while ((match = blockRe.exec(css)) !== null) {
    const openIdx = css.indexOf('{', match.index);
    if (openIdx === -1) continue;
    const closeIdx = findMatchingBraceForTokens(css, openIdx);
    if (closeIdx === -1) continue;

    const body = css.slice(openIdx + 1, closeIdx);
    // Extract --name: value; pairs from this body
    const declRe = /--([a-z][a-z0-9-]*)\s*:\s*([^;]+);/gi;
    let declMatch: RegExpExecArray | null;
    while ((declMatch = declRe.exec(body)) !== null) {
      const name = declMatch[1].trim();
      const value = declMatch[2].trim();
      // Skip if already seen (first occurrence wins)
      if (!pairs.some(p => p.name === name)) {
        pairs.push({ name, value });
      }
    }
  }

  return pairs;
}

function findMatchingBraceForTokens(css: string, openIdx: number): number {
  let depth = 1;
  let i = openIdx + 1;
  while (i < css.length) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') {
      depth--;
      if (depth === 0) return i;
    }
    i++;
  }
  return -1;
}

// Maps group names back to CSS var name prefixes (reverse of classifyVar)
const GROUP_TO_PREFIX: Record<string, string> = {
  color: '',           // color tokens emit bare name: --brand, --background
  radius: 'radius',   // radius.lg -> --radius-lg, radius.default -> --radius
  font: 'font',       // font.sans -> --font-sans
  shadow: 'shadow',   // shadow.sm -> --shadow-sm
  spacing: 'spacing', // spacing.lg -> --spacing-lg
  motion: 'duration', // motion.duration.fast -> --duration-fast (simplified)
};

function tokenKeyToCssName(group: string, key: string): string {
  const prefix = GROUP_TO_PREFIX[group];

  // No prefix mapping -> use key as-is (generic groups)
  if (prefix === undefined) return key;

  // Empty prefix -> bare name (color group)
  if (prefix === '') return key;

  // 'default' key -> bare prefix (e.g., radius.default -> --radius)
  if (key === 'default') return prefix;

  // Normal case: prefix-suffix (e.g., radius.lg -> radius-lg)
  return `${prefix}-${key}`;
}

/**
 * Write a W3C-style grouped token object back to CSS.
 *
 * If options.existing is provided, surgically replaces matching variable
 * values in the existing CSS and appends new ones to the :root block.
 * All non-managed declarations are preserved.
 *
 * If no existing CSS is provided, generates a fresh :root { ... } block.
 */
export function writeTokensToCss(tokens: Tokens, options?: { existing?: string }): string {
  // Flatten tokens to --name: value pairs
  const flatVars = flattenTokens(tokens);

  if (!options?.existing) {
    // Generate fresh CSS
    const lines = flatVars.map(({ name, value }) => `  --${name}: ${value};`);
    return `:root {\n${lines.join('\n')}\n}\n`;
  }

  // Surgical replacement in existing CSS
  return surgicalReplace(options.existing, flatVars);
}

function flattenTokens(tokens: Tokens): Array<{ name: string; value: string }> {
  const result: Array<{ name: string; value: string }> = [];

  for (const [group, groupObj] of Object.entries(tokens)) {
    for (const [key, tokenVal] of Object.entries(groupObj)) {
      if (key === '$type') continue;
      if (!tokenVal || typeof tokenVal !== 'object' || !('$value' in tokenVal)) continue;
      const cssName = tokenKeyToCssName(group, key);
      result.push({ name: cssName, value: (tokenVal as TokenValue).$value });
    }
  }

  return result;
}

/**
 * Find the :root { ... } block in existing CSS, replace matching vars
 * in-place, and append any new vars that don't already exist.
 * Preserves all other declarations and CSS outside the :root block.
 */
function surgicalReplace(
  css: string,
  vars: Array<{ name: string; value: string }>,
): string {
  // Find :root block
  const rootRe = /:root\s*\{/;
  const rootMatch = rootRe.exec(css);
  if (!rootMatch) {
    // No :root block -- prepend a new one with our vars, keep existing CSS
    const lines = vars.map(({ name, value }) => `  --${name}: ${value};`);
    return `:root {\n${lines.join('\n')}\n}\n${css}`;
  }

  const openIdx = css.indexOf('{', rootMatch.index);
  const closeIdx = findMatchingBraceForTokens(css, openIdx);
  if (closeIdx === -1) {
    // Malformed CSS -- fall back to prepend
    const lines = vars.map(({ name, value }) => `  --${name}: ${value};`);
    return `:root {\n${lines.join('\n')}\n}\n${css}`;
  }

  let body = css.slice(openIdx + 1, closeIdx);
  const remaining = new Map(vars.map(v => [v.name, v.value]));

  // Replace existing declarations in-place (collect positions first)
  const declRe = /--([\w-]+)\s*:\s*([^;]+);/g;
  const replacements: Array<{ start: number; end: number; name: string }> = [];
  let declMatch: RegExpExecArray | null;
  while ((declMatch = declRe.exec(body)) !== null) {
    const declName = declMatch[1];
    if (remaining.has(declName)) {
      replacements.push({
        start: declMatch.index,
        end: declMatch.index + declMatch[0].length,
        name: declName,
      });
    }
  }

  // Apply replacements from end to start to preserve offsets
  for (let i = replacements.length - 1; i >= 0; i--) {
    const r = replacements[i];
    const newValue = remaining.get(r.name)!;
    const newDecl = `--${r.name}: ${newValue};`;
    body = body.slice(0, r.start) + newDecl + body.slice(r.end);
    remaining.delete(r.name);
  }

  // Append any new vars that didn't exist in the original
  if (remaining.size > 0) {
    // Detect indentation from the body
    const indentMatch = body.match(/\n(\s+)--/);
    const indent = indentMatch ? indentMatch[1] : '  ';

    const newLines = Array.from(remaining.entries())
      .map(([name, value]) => `\n${indent}--${name}: ${value};`)
      .join('');

    // Insert before trailing whitespace/newline
    const trailingMatch = body.match(/(\s*)$/);
    const trailing = trailingMatch?.[1] ?? '';
    const insertAt = body.length - trailing.length;
    body = body.slice(0, insertAt) + newLines + body.slice(insertAt);
  }

  return css.slice(0, openIdx + 1) + body + css.slice(closeIdx);
}
