// Generated by design-engine /design-settings-page
// Settings page logic — runs in the browser at /__design/

type TokenValue = { $value: string };
type TokenGroup = { $type?: string; [name: string]: TokenValue | string | undefined };
type Tokens = { [group: string]: TokenGroup };

type FontEntry = { family: string; category: string; weights?: number[]; axisRange?: string };
type CatalogState = 'idle' | 'loading' | 'ready' | 'failed';

const GROUP_TO_PREFIX: Record<string, string> = {
  color: '', radius: 'radius', font: 'font',
  shadow: 'shadow', spacing: 'spacing', motion: 'duration',
};

const COLOR_RE = /^#(?:[0-9a-f]{3,8})$/i;
const COLOR_FUNC_RE = /^(?:oklch|oklab|hsl|hsla|rgb|rgba)\s*\(/i;

const OFFLINE_FONTS: FontEntry[] = [
  { family: 'Inter', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'Geist', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Pretendard', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'DM Sans', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Manrope', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'Plus Jakarta Sans', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'IBM Plex Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Roboto', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Open Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Source Sans 3', category: 'sans-serif', weights: [400, 600, 700] },
  { family: 'JetBrains Mono', category: 'monospace', weights: [400, 500, 700] },
  { family: 'Space Grotesk', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Outfit', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Albert Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
];

const GOOGLE_FONTS_PROXY_URL = '/__design/api/google-fonts';
const CATALOG_CACHE_KEY = 'de-google-fonts-catalog-v2';

let fontEntries: FontEntry[] = OFFLINE_FONTS;
let catalogState: CatalogState = 'idle';
let catalogPromise: Promise<FontEntry[]> | null = null;

let tokens: Tokens | null = null;
let saveTimer: number | null = null;
let lastSaveError: string | null = null;
let statusEl: HTMLElement | null = null;

const root = document.getElementById('de-root')!;
const tokensStyle = document.getElementById('de-tokens') as HTMLStyleElement;

bootstrap();

async function bootstrap() {
  try {
    const res = await fetch('/__design/api/tokens');
    if (!res.ok) {
      const body = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(body.message ?? 'Failed to load tokens');
    }
    tokens = await res.json();
    render();
  } catch (e) {
    renderError(String((e as Error).message));
  }
}

function renderError(msg: string) {
  while (root.firstChild) root.removeChild(root.firstChild);
  const page = document.createElement('div');
  page.className = 'de-page';
  const title = document.createElement('h1');
  title.className = 'de-title';
  title.textContent = 'Design Engine Settings';
  const box = document.createElement('div');
  box.className = 'de-error-box';
  const p1 = document.createElement('p');
  const strong = document.createElement('strong');
  strong.textContent = 'Could not load tokens.json';
  p1.appendChild(strong);
  const p2 = document.createElement('p');
  p2.textContent = msg;
  box.appendChild(p1);
  box.appendChild(p2);
  page.appendChild(title);
  page.appendChild(box);
  root.appendChild(page);
}

function render() {
  if (!tokens) {
    while (root.firstChild) root.removeChild(root.firstChild);
    const loading = document.createElement('div');
    loading.className = 'de-loading';
    loading.textContent = 'Loading...';
    root.appendChild(loading);
    return;
  }
  updateTokensStyle();
  while (root.firstChild) root.removeChild(root.firstChild);
  root.appendChild(buildPage());
}

function tokenKeyToCssName(group: string, key: string): string {
  const prefix = GROUP_TO_PREFIX[group];
  if (prefix === undefined) return key;
  if (prefix === '') return key;
  if (key === 'default') return prefix;
  return `${prefix}-${key}`;
}

function isColorValue(value: string): boolean {
  return COLOR_RE.test(value) || COLOR_FUNC_RE.test(value);
}

function getTokenValue(group: string, key: string): string {
  if (!tokens || !tokens[group]) return '';
  const entry = tokens[group][key];
  if (!entry || typeof entry !== 'object' || !('$value' in entry)) return '';
  return entry.$value;
}

function getFontFamily(): string {
  if (!tokens?.font) return 'Inter';
  for (const [key, val] of Object.entries(tokens.font)) {
    if (key === '$type') continue;
    if (val && typeof val === 'object' && '$value' in val) {
      const raw = val.$value;
      return raw.split(',')[0].trim().replace(/^['"]|['"]$/g, '');
    }
  }
  return 'Inter';
}

function updateTokensStyle() {
  if (!tokens) return;
  const lines: string[] = [];
  for (const [group, groupObj] of Object.entries(tokens)) {
    for (const [key, val] of Object.entries(groupObj)) {
      if (key === '$type') continue;
      if (!val || typeof val !== 'object' || !('$value' in val)) continue;
      const cssName = tokenKeyToCssName(group, key);
      lines.push(`  --de-${cssName}: ${val.$value};`);
    }
  }
  const fontFamily = getFontFamily();
  tokensStyle.textContent = `:root {\n${lines.join('\n')}\n}\nbody { font-family: '${fontFamily}', system-ui, sans-serif; background: var(--de-background); color: var(--de-foreground); margin: 0; min-height: 100vh; }`;
}

function buildPage(): HTMLElement {
  if (!tokens) return document.createElement('div');
  const page = document.createElement('div');
  page.className = 'de-page';

  page.appendChild(buildHeader());
  for (const group of Object.keys(tokens)) {
    page.appendChild(buildGroupEditor(group));
  }
  page.appendChild(buildFontPicker());
  page.appendChild(buildDemoShowcase());
  page.appendChild(buildCssFallback());

  return page;
}

function buildHeader(): HTMLElement {
  const header = document.createElement('header');
  header.className = 'de-header';

  const left = document.createElement('div');
  const title = document.createElement('h1');
  title.className = 'de-title';
  title.textContent = 'Design Engine Settings';
  const subtitle = document.createElement('p');
  subtitle.className = 'de-subtitle';
  subtitle.textContent = 'Edit tokens — changes save and reload automatically.';
  left.appendChild(title);
  left.appendChild(subtitle);

  const right = document.createElement('div');
  right.style.display = 'flex';
  right.style.alignItems = 'center';
  right.style.gap = '12px';

  statusEl = document.createElement('span');
  statusEl.className = 'de-status';
  statusEl.id = 'de-status';
  right.appendChild(statusEl);

  if (lastSaveError) {
    const err = document.createElement('span');
    err.className = 'de-status de-status-error';
    err.textContent = `Error: ${lastSaveError}`;
    const retry = document.createElement('button');
    retry.textContent = 'Retry';
    retry.style.marginLeft = '8px';
    retry.addEventListener('click', () => { lastSaveError = null; flushSave(); });
    err.appendChild(retry);
    right.appendChild(err);
  }

  header.appendChild(left);
  header.appendChild(right);
  return header;
}

function buildGroupEditor(group: string): HTMLElement {
  if (!tokens) return document.createElement('div');
  const groupObj = tokens[group];
  const groupType = groupObj.$type;
  const isColor = groupType === 'color';

  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = group.charAt(0).toUpperCase() + group.slice(1);
  card.appendChild(h2);

  for (const [key, val] of Object.entries(groupObj)) {
    if (key === '$type') continue;
    if (!val || typeof val !== 'object' || !('$value' in val)) continue;
    const tokenVal = val as TokenValue;
    const cssName = tokenKeyToCssName(group, key);
    const valueIsColor = isColor || isColorValue(tokenVal.$value);

    const row = document.createElement('div');
    row.className = 'de-color-row';

    const label = document.createElement('label');
    label.textContent = `--${cssName}`;

    if (valueIsColor) {
      const colorIn = document.createElement('input');
      colorIn.type = 'color';
      colorIn.value = tokenVal.$value;

      const textIn = document.createElement('input');
      textIn.type = 'text';
      textIn.value = tokenVal.$value;

      const onChange = (newValue: string) => {
        colorIn.value = newValue;
        textIn.value = newValue;
        updateToken(group, key, newValue);
      };
      colorIn.addEventListener('input', () => onChange(colorIn.value));
      textIn.addEventListener('input', () => onChange(textIn.value));
      colorIn.addEventListener('blur', () => flushSave());
      textIn.addEventListener('blur', () => flushSave());

      row.appendChild(label);
      row.appendChild(colorIn);
      row.appendChild(textIn);
    } else {
      const textIn = document.createElement('input');
      textIn.type = 'text';
      textIn.value = tokenVal.$value;
      textIn.style.flex = '1';

      textIn.addEventListener('input', () => updateToken(group, key, textIn.value));
      textIn.addEventListener('blur', () => flushSave());

      row.appendChild(label);
      row.appendChild(textIn);
    }

    card.appendChild(row);
  }

  return card;
}

async function loadGoogleFontsCatalog(): Promise<FontEntry[]> {
  if (catalogPromise) return catalogPromise;

  try {
    const cached = sessionStorage.getItem(CATALOG_CACHE_KEY);
    if (cached) {
      const parsed = JSON.parse(cached) as FontEntry[];
      if (Array.isArray(parsed) && parsed.length > 0) {
        fontEntries = parsed;
        catalogState = 'ready';
        return parsed;
      }
    }
  } catch { /* corrupt cache -- refetch */ }

  catalogPromise = (async () => {
    const res = await fetch(GOOGLE_FONTS_PROXY_URL);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (!Array.isArray(data) || data.length === 0) throw new Error('Empty catalog');
    try { sessionStorage.setItem(CATALOG_CACHE_KEY, JSON.stringify(data)); } catch { /* quota -- skip cache */ }
    return data as FontEntry[];
  })();
  return catalogPromise;
}

function buildFontPicker(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Font';
  card.appendChild(h2);

  const wrap = document.createElement('div');
  wrap.className = 'de-relative';

  const currentFont = getFontFamily();
  const input = document.createElement('input');
  input.type = 'text';
  input.className = 'de-font-input';
  input.placeholder = 'Type a font name...';
  input.value = currentFont;
  input.autocomplete = 'off';

  const suggestions = document.createElement('div');
  suggestions.className = 'de-font-suggestions';
  suggestions.hidden = true;

  const renderSuggestions = (q: string) => {
    while (suggestions.firstChild) suggestions.removeChild(suggestions.firstChild);
    const ql = q.toLowerCase().trim();
    const matches = fontEntries.filter(f => f.family.toLowerCase().includes(ql)).slice(0, 20);

    if (catalogState === 'loading') {
      const hint = document.createElement('div');
      hint.className = 'de-font-cat';
      hint.style.cssText = 'padding: 8px 12px;';
      hint.textContent = 'Loading Google Fonts catalog...';
      suggestions.appendChild(hint);
    } else if (catalogState === 'failed') {
      const hint = document.createElement('div');
      hint.className = 'de-font-cat';
      hint.style.cssText = 'padding: 8px 12px;';
      hint.textContent = 'Could not load the full Google Fonts catalog. Showing common fonts only.';
      suggestions.appendChild(hint);
    }

    if (matches.length === 0 && catalogState !== 'loading' && catalogState !== 'failed') {
      suggestions.hidden = true;
      return;
    }
    suggestions.hidden = false;
    for (const f of matches) {
      const btn = document.createElement('button');
      const fam = document.createElement('span');
      fam.style.fontFamily = `'${f.family}', system-ui`;
      fam.textContent = f.family;
      const cat = document.createElement('span');
      cat.className = 'de-font-cat';
      cat.textContent = f.category;
      btn.appendChild(fam);
      btn.appendChild(cat);
      btn.addEventListener('mousedown', e => {
        e.preventDefault();
        input.value = f.family;
        updateFontToken(f.family);
        suggestions.hidden = true;
        flushSave();
      });
      suggestions.appendChild(btn);
    }
  };

  const ensureCatalog = async () => {
    if (catalogState === 'ready' || catalogState === 'failed' || catalogState === 'loading') return;
    catalogState = 'loading';
    renderSuggestions(input.value);
    try {
      const entries = await loadGoogleFontsCatalog();
      fontEntries = entries;
      catalogState = 'ready';
    } catch {
      catalogState = 'failed';
    }
    if (document.activeElement === input) renderSuggestions(input.value);
  };

  input.addEventListener('focus', () => {
    renderSuggestions(input.value);
    void ensureCatalog();
  });
  input.addEventListener('input', () => {
    renderSuggestions(input.value);
    if (tokens) {
      updateFontTokenPreviewOnly(input.value);
      const pre = document.getElementById('de-css-output');
      if (pre) pre.textContent = generateCss();
    }
  });
  input.addEventListener('blur', () => {
    updateFontToken(input.value);
    setTimeout(() => { suggestions.hidden = true; }, 150);
    flushSave();
  });

  wrap.appendChild(input);
  wrap.appendChild(suggestions);
  card.appendChild(wrap);
  return card;
}

function buildDemoShowcase(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Live Preview';
  card.appendChild(h2);

  const demo = document.createElement('div');
  demo.className = 'de-demo';

  const typoSection = document.createElement('section');
  const h1 = document.createElement('h1');
  h1.style.cssText = 'font-size: 32px; font-weight: 700; margin: 0;';
  h1.textContent = 'Display heading';
  const sectionH2 = document.createElement('h2');
  sectionH2.style.cssText = 'font-size: 20px; font-weight: 600; margin: 8px 0;';
  sectionH2.textContent = 'Section heading';
  const para = document.createElement('p');
  para.style.cssText = 'font-size: 14px; margin: 8px 0;';
  para.textContent = 'Body paragraph showing how foreground color and the primary font interact at default reading size.';
  const small = document.createElement('p');
  small.style.cssText = 'font-size: 12px; opacity: 0.7; margin: 8px 0;';
  small.textContent = 'Small label / muted text';
  const code = document.createElement('code');
  code.style.cssText = 'font-size: 12px; padding: 2px 6px; background: color-mix(in oklab, var(--de-foreground) 10%, transparent); border-radius: 4px; font-family: ui-monospace, monospace;';
  code.textContent = 'inline code';
  typoSection.appendChild(h1);
  typoSection.appendChild(sectionH2);
  typoSection.appendChild(para);
  typoSection.appendChild(small);
  typoSection.appendChild(code);

  const buttonsRow = document.createElement('div');
  buttonsRow.className = 'de-demo-row';
  for (const [label, cls] of [['Brand', 'de-btn-brand'], ['Primary', 'de-btn-primary'], ['Destructive', 'de-btn-destructive'], ['Outline', 'de-btn-outline']] as const) {
    const b = document.createElement('button');
    b.className = `de-btn ${cls}`;
    b.textContent = label;
    buttonsRow.appendChild(b);
  }

  const chipsRow = document.createElement('div');
  chipsRow.className = 'de-demo-row';
  for (const [label, cls] of [['Success', 'de-chip-success'], ['Warning', 'de-chip-warning'], ['Error', 'de-chip-error'], ['Info', 'de-chip-info']] as const) {
    const c = document.createElement('span');
    c.className = `de-chip ${cls}`;
    c.textContent = label;
    chipsRow.appendChild(c);
  }

  const form = document.createElement('div');
  form.className = 'de-form';
  const input = document.createElement('input');
  input.type = 'text';
  input.placeholder = 'Text input';
  const select = document.createElement('select');
  for (const opt of ['Option A', 'Option B']) {
    const o = document.createElement('option');
    o.textContent = opt;
    select.appendChild(o);
  }
  form.appendChild(input);
  form.appendChild(select);

  const stat = document.createElement('div');
  stat.className = 'de-stat-card';
  const statLabel = document.createElement('p');
  statLabel.className = 'de-stat-label';
  statLabel.textContent = 'REVENUE';
  const statValue = document.createElement('p');
  statValue.className = 'de-stat-value';
  statValue.textContent = '$48.2K';
  const statDelta = document.createElement('p');
  statDelta.className = 'de-stat-delta';
  statDelta.textContent = '+8.2% vs last month';
  stat.appendChild(statLabel);
  stat.appendChild(statValue);
  stat.appendChild(statDelta);

  demo.appendChild(typoSection);
  demo.appendChild(buttonsRow);
  demo.appendChild(chipsRow);
  demo.appendChild(form);
  demo.appendChild(stat);
  card.appendChild(demo);
  return card;
}

function buildCssFallback(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Generated CSS (fallback)';
  card.appendChild(h2);
  const note = document.createElement('p');
  note.style.cssText = 'font-size: 12px; opacity: 0.7; margin: 0 0 12px 0;';
  note.textContent = 'Live write-back is active. Use this snippet for sharing or as a fallback.';
  card.appendChild(note);
  const pre = document.createElement('pre');
  pre.className = 'de-pre';
  pre.id = 'de-css-output';
  pre.textContent = generateCss();
  card.appendChild(pre);
  const copy = document.createElement('button');
  copy.className = 'de-btn de-btn-outline';
  copy.style.marginTop = '12px';
  copy.textContent = 'Copy CSS';
  copy.addEventListener('click', () => navigator.clipboard.writeText(generateCss()));
  card.appendChild(copy);
  return card;
}

function generateCss(): string {
  if (!tokens) return '';
  const lines: string[] = [];
  for (const [group, groupObj] of Object.entries(tokens)) {
    for (const [key, val] of Object.entries(groupObj)) {
      if (key === '$type') continue;
      if (!val || typeof val !== 'object' || !('$value' in val)) continue;
      const cssName = tokenKeyToCssName(group, key);
      lines.push(`  --${cssName}: ${val.$value};`);
    }
  }
  return `:root {\n${lines.join('\n')}\n}`;
}

function updateToken(group: string, key: string, value: string) {
  if (!tokens || !tokens[group]) return;
  (tokens[group][key] as TokenValue) = { $value: value };
  updateTokensStyle();
  const pre = document.getElementById('de-css-output');
  if (pre) pre.textContent = generateCss();
  scheduleSave();
}

function updateFontToken(name: string) {
  if (!tokens) return;
  if (!tokens.font) tokens.font = { $type: 'fontFamily' };
  const formatted = `'${name}', system-ui, -apple-system, BlinkMacSystemFont, sans-serif`;
  const firstKey = Object.keys(tokens.font).find(k => k !== '$type');
  if (firstKey) {
    (tokens.font[firstKey] as TokenValue) = { $value: formatted };
  } else {
    (tokens.font as any).primary = { $value: formatted };
  }
  updateTokensStyle();
  const pre = document.getElementById('de-css-output');
  if (pre) pre.textContent = generateCss();
  scheduleSave();
}

function updateFontTokenPreviewOnly(name: string) {
  if (!tokens) return;
  if (!tokens.font) tokens.font = { $type: 'fontFamily' };
  const formatted = `'${name}', system-ui, -apple-system, BlinkMacSystemFont, sans-serif`;
  const firstKey = Object.keys(tokens.font).find(k => k !== '$type');
  if (firstKey) {
    (tokens.font[firstKey] as TokenValue) = { $value: formatted };
  } else {
    (tokens.font as any).primary = { $value: formatted };
  }
  updateTokensStyle();
}

function setStatus(s: 'idle' | 'saving' | 'saved') {
  if (!statusEl) return;
  if (s === 'idle') { statusEl.textContent = ''; statusEl.className = 'de-status'; return; }
  if (s === 'saving') { statusEl.textContent = 'Saving...'; statusEl.className = 'de-status de-status-saving'; return; }
  if (s === 'saved') { statusEl.textContent = 'Saved'; statusEl.className = 'de-status de-status-saved'; }
}

function scheduleSave() {
  if (saveTimer !== null) window.clearTimeout(saveTimer);
  saveTimer = window.setTimeout(() => { flushSave(); }, 500);
}

async function flushSave() {
  if (!tokens) return;
  if (saveTimer !== null) { window.clearTimeout(saveTimer); saveTimer = null; }
  setStatus('saving');
  try {
    const res = await fetch('/__design/api/tokens', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(tokens),
    });
    const body = await res.json();
    if (body.tokens) tokens = body.tokens;
    if (!res.ok || !body.ok) throw new Error(body.message ?? `HTTP ${res.status}`);
    lastSaveError = null;
    updateTokensStyle();
    setStatus('saved');
    window.setTimeout(() => { if (statusEl?.textContent === 'Saved') setStatus('idle'); }, 1500);
  } catch (e) {
    lastSaveError = String((e as Error).message);
    render();
  }
}
