// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Astro integration: serves the design-engine settings page and token API at /__design/*
// Dev-only — astro:server:setup runs only when `astro dev` is active, not during `astro build`.

import type { AstroIntegration } from 'astro';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import {
  writeTokensToCss,
  type Tokens
} from './theme-io.ts';
import { fetchGoogleFontsCatalog } from './google-fonts-catalog.ts';

function validateW3CShape(body: unknown): asserts body is Tokens {
  if (!body || typeof body !== 'object') throw new Error('Body must be a token object');
  for (const [group, groupObj] of Object.entries(body as Record<string, unknown>)) {
    if (!groupObj || typeof groupObj !== 'object') throw new Error(`Group "${group}" must be an object`);
    for (const [key, val] of Object.entries(groupObj as Record<string, unknown>)) {
      if (key === '$type') continue;
      if (!val || typeof val !== 'object' || !('$value' in (val as Record<string, unknown>))) {
        throw new Error(`Token "${group}.${key}" must have a $value property`);
      }
    }
  }
}

export async function handleGetTokens({ projectRoot }: { projectRoot: string }): Promise<Tokens> {
  const tokensPath = resolve(projectRoot, 'tokens.json');
  const raw = await readFile(tokensPath, 'utf8');
  return JSON.parse(raw);
}

export async function handlePostTokens({ projectRoot, body }: { projectRoot: string; body: unknown }): Promise<{ tokens: Tokens }> {
  validateW3CShape(body);
  const tokens = body as Tokens;

  const tokensPath = resolve(projectRoot, 'tokens.json');
  await writeFile(tokensPath, JSON.stringify(tokens, null, 2) + '\n', 'utf8');

  const configPath = resolve(projectRoot, '.design-rules', 'config.json');
  const config = JSON.parse(await readFile(configPath, 'utf8'));
  const themeFile = config.themeFile;

  if (themeFile) {
    const themePath = resolve(projectRoot, themeFile);
    const existingCss = await readFile(themePath, 'utf8');
    const newCss = writeTokensToCss(tokens, { existing: existingCss });
    await writeFile(themePath, newCss, 'utf8');
  }

  return { tokens };
}

export default function designEngine(_options: {} = {}): AstroIntegration {
  const here = dirname(fileURLToPath(import.meta.url));

  return {
    name: 'design-engine-settings',
    hooks: {
      'astro:server:setup': ({ server }) => {
        const root = server.config.root;

        server.middlewares.use(async (req, res, next) => {
          const url = req.url ?? '';

          if (!url.startsWith('/__design')) return next();

          if (url === '/__design') {
            res.statusCode = 302;
            res.setHeader('location', '/__design/');
            res.end();
            return;
          }

          if (url === '/__design/' && req.method === 'GET') {
            const html = await readFile(resolve(here, '__design-page.html'), 'utf8');
            res.statusCode = 200;
            res.setHeader('content-type', 'text/html; charset=utf-8');
            res.end(html);
            return;
          }

          if (url === '/__design/page.js' && req.method === 'GET') {
            const js = await readFile(resolve(here, '__design-page.js'), 'utf8');
            res.statusCode = 200;
            res.setHeader('content-type', 'text/javascript; charset=utf-8');
            res.end(js);
            return;
          }

          if (url === '/__design/api/google-fonts' && req.method === 'GET') {
            res.setHeader('content-type', 'application/json');
            try {
              const fonts = await fetchGoogleFontsCatalog();
              res.statusCode = 200;
              res.end(JSON.stringify(fonts));
            } catch (err) {
              res.statusCode = 503;
              res.end(JSON.stringify({
                ok: false,
                error: 'catalog_unavailable',
                message: 'Failed to load Google Fonts catalog',
              }));
            }
            return;
          }

          // GET tokens
          if (url === '/__design/api/tokens' && req.method === 'GET') {
            res.setHeader('content-type', 'application/json');
            try {
              const tokens = await handleGetTokens({ projectRoot: root });
              res.end(JSON.stringify(tokens));
            } catch (err) {
              res.statusCode = 409;
              res.end(JSON.stringify({ error: 'read_failed', message: String(err) }));
            }
            return;
          }

          // POST tokens
          if (url === '/__design/api/tokens' && req.method === 'POST') {
            let body = '';
            req.setEncoding('utf8');
            for await (const chunk of req) body += chunk;
            let parsed: unknown;
            try {
              parsed = JSON.parse(body);
            } catch {
              res.statusCode = 400;
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: false, error: 'bad_request', message: 'Invalid JSON' }));
              return;
            }
            try {
              const result = await handlePostTokens({ projectRoot: root, body: parsed });
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: true, tokens: result.tokens }));
            } catch (err) {
              res.statusCode = 422;
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: false, error: 'validation_failed', message: String(err) }));
            }
            return;
          }

          if (
            url === '/__design/api/tokens' ||
            url === '/__design/api/google-fonts' ||
            url === '/__design/' ||
            url === '/__design/page.js'
          ) {
            res.statusCode = 405;
            res.end();
            return;
          }

          res.statusCode = 404;
          res.end();
        });
      },
    },
  };
}
