// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Astro integration: serves the design-engine settings page and token API at /__design/*
// Dev-only — astro:server:setup runs only when `astro dev` is active, not during `astro build`.

import type { AstroIntegration } from 'astro';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile } from 'node:fs/promises';
import {
  readTokens, writeTokens, writeFontImports, buildGoogleFontsUrl,
  type Mode, type ColorTokens
} from './theme-io';
import { fetchGoogleFontsCatalog } from './google-fonts-catalog';

export type DesignEngineIntegrationOptions = {
  themePath?: string;
  fontsPath?: string;
};

const DEFAULT_THEME = 'src/styles/theme.css';
const DEFAULT_FONTS = 'src/styles/fonts.css';

export default function designEngine(options: DesignEngineIntegrationOptions = {}): AstroIntegration {
  const themePath = options.themePath ?? DEFAULT_THEME;
  const fontsPath = options.fontsPath ?? DEFAULT_FONTS;
  const here = dirname(fileURLToPath(import.meta.url));

  return {
    name: 'design-engine-settings',
    hooks: {
      'astro:server:setup': ({ server }) => {
        const root = server.config.root;
        const fullThemePath = resolve(root, themePath);
        const fullFontsPath = resolve(root, fontsPath);

        server.middlewares.use(async (req, res, next) => {
          const url = req.url ?? '';

          if (!url.startsWith('/__design')) return next();

          if (url === '/__design') {
            res.statusCode = 302;
            res.setHeader('location', '/__design/');
            res.end();
            return;
          }

          if (url === '/__design/' && req.method === 'GET') {
            const html = await readFile(resolve(here, '__design-page.html'), 'utf8');
            res.statusCode = 200;
            res.setHeader('content-type', 'text/html; charset=utf-8');
            res.end(html);
            return;
          }

          if (url === '/__design/page.js' && req.method === 'GET') {
            const js = await readFile(resolve(here, '__design-page.js'), 'utf8');
            res.statusCode = 200;
            res.setHeader('content-type', 'text/javascript; charset=utf-8');
            res.end(js);
            return;
          }

          if (url === '/__design/api/google-fonts' && req.method === 'GET') {
            res.setHeader('content-type', 'application/json');
            try {
              const fonts = await fetchGoogleFontsCatalog();
              res.statusCode = 200;
              res.end(JSON.stringify(fonts));
            } catch (err) {
              res.statusCode = 503;
              res.end(JSON.stringify({
                ok: false,
                error: 'catalog_unavailable',
                message: 'Failed to load Google Fonts catalog',
              }));
            }
            return;
          }

          if (url === '/__design/api/tokens' && req.method === 'GET') {
            const result = await readTokens(fullThemePath);
            res.setHeader('content-type', 'application/json');
            if (result.ok) {
              res.end(JSON.stringify(result.tokens));
            } else {
              res.statusCode = 409;
              res.end(JSON.stringify({ error: result.error, message: result.message }));
            }
            return;
          }

          if (url === '/__design/api/tokens' && req.method === 'POST') {
            let body = '';
            req.setEncoding('utf8');
            for await (const chunk of req) body += chunk;
            let parsed: { mode: Mode; colors: ColorTokens; font?: string; fontImport?: { name: string; weights?: number[]; axisRange?: string } | null };
            try {
              parsed = JSON.parse(body);
            } catch {
              res.statusCode = 400;
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: false, error: 'bad_request', message: 'Invalid JSON' }));
              return;
            }

            const writeResult = await writeTokens(fullThemePath, parsed.mode, parsed.colors, parsed.font);
            if (!writeResult.ok) {
              res.statusCode = 409;
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: false, error: writeResult.error, message: writeResult.message }));
              return;
            }

            if (parsed.fontImport && parsed.fontImport.name) {
              const importUrl = buildGoogleFontsUrl(parsed.fontImport.name, parsed.fontImport.weights, parsed.fontImport.axisRange);
              const fontResult = await writeFontImports(fullFontsPath, [{ name: parsed.fontImport.name, url: importUrl }]);
              if (!fontResult.ok) {
                res.statusCode = 207;
                res.setHeader('content-type', 'application/json');
                res.end(JSON.stringify({ ok: false, error: 'font_write_failed', message: fontResult.message, tokens: writeResult.tokens }));
                return;
              }
            } else if (parsed.fontImport === null) {
              const fontResult = await writeFontImports(fullFontsPath, []);
              if (!fontResult.ok) {
                res.statusCode = 207;
                res.setHeader('content-type', 'application/json');
                res.end(JSON.stringify({ ok: false, error: 'font_write_failed', message: fontResult.message, tokens: writeResult.tokens }));
                return;
              }
            }

            res.setHeader('content-type', 'application/json');
            res.end(JSON.stringify({ ok: true, tokens: writeResult.tokens }));
            return;
          }

          if (
            url === '/__design/api/tokens' ||
            url === '/__design/api/google-fonts' ||
            url === '/__design/' ||
            url === '/__design/page.js'
          ) {
            res.statusCode = 405;
            res.end();
            return;
          }

          res.statusCode = 404;
          res.end();
        });
      },
    },
  };
}
