// Generated by design-engine /design-settings-page
// Settings page logic — runs in the browser at /__design/

const MANAGED_COLOR_KEYS = ['brand', 'primary', 'background', 'card', 'foreground', 'destructive', 'success', 'warning', 'info'] as const;
type ColorKey = typeof MANAGED_COLOR_KEYS[number];
type Mode = 'light' | 'dark';
type ColorTokens = Record<ColorKey, string>;
type TokenSet = { light: ColorTokens; dark: ColorTokens; font: string };

type FontEntry = { family: string; category: string; weights?: number[]; axisRange?: string };
type CatalogState = 'idle' | 'loading' | 'ready' | 'failed';

const OFFLINE_FONTS: FontEntry[] = [
  { family: 'Inter', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'Geist', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Pretendard', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'DM Sans', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Manrope', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'Plus Jakarta Sans', category: 'sans-serif', weights: [400, 500, 600, 700, 800] },
  { family: 'IBM Plex Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Roboto', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Open Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Source Sans 3', category: 'sans-serif', weights: [400, 600, 700] },
  { family: 'JetBrains Mono', category: 'monospace', weights: [400, 500, 700] },
  { family: 'Space Grotesk', category: 'sans-serif', weights: [400, 500, 700] },
  { family: 'Outfit', category: 'sans-serif', weights: [400, 500, 600, 700] },
  { family: 'Albert Sans', category: 'sans-serif', weights: [400, 500, 600, 700] },
];

const GOOGLE_FONTS_METADATA_URL = 'https://fonts.google.com/metadata/fonts';
const CATALOG_CACHE_KEY = 'de-google-fonts-catalog-v1';

let fontEntries: FontEntry[] = OFFLINE_FONTS;
let catalogState: CatalogState = 'idle';
let catalogPromise: Promise<FontEntry[]> | null = null;

let tokens: TokenSet | null = null;
let mode: Mode = 'light';
let saveTimer: number | null = null;
let pendingFontImport: { name: string; weights?: number[]; axisRange?: string } | null | undefined = undefined;
let lastSaveError: string | null = null;
let statusEl: HTMLElement | null = null;

const root = document.getElementById('de-root')!;
const tokensStyle = document.getElementById('de-tokens') as HTMLStyleElement;

bootstrap();

async function bootstrap() {
  try {
    const res = await fetch('/__design/api/tokens');
    if (!res.ok) {
      const body = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(body.message ?? 'Failed to load tokens');
    }
    tokens = await res.json();
    render();
  } catch (e) {
    renderError(String((e as Error).message));
  }
}

function renderError(msg: string) {
  while (root.firstChild) root.removeChild(root.firstChild);
  const page = document.createElement('div');
  page.className = 'de-page';
  const title = document.createElement('h1');
  title.className = 'de-title';
  title.textContent = 'Design Engine Settings';
  const box = document.createElement('div');
  box.className = 'de-error-box';
  const p1 = document.createElement('p');
  const strong = document.createElement('strong');
  strong.textContent = 'Could not load theme.css';
  p1.appendChild(strong);
  const p2 = document.createElement('p');
  p2.textContent = msg;
  box.appendChild(p1);
  box.appendChild(p2);
  page.appendChild(title);
  page.appendChild(box);
  root.appendChild(page);
}

function render() {
  if (!tokens) {
    while (root.firstChild) root.removeChild(root.firstChild);
    const loading = document.createElement('div');
    loading.className = 'de-loading';
    loading.textContent = 'Loading...';
    root.appendChild(loading);
    return;
  }
  applyModeClass();
  updateTokensStyle();
  while (root.firstChild) root.removeChild(root.firstChild);
  root.appendChild(buildPage());
}

function applyModeClass() {
  if (mode === 'dark') document.documentElement.classList.add('de-dark');
  else document.documentElement.classList.remove('de-dark');
}

function updateTokensStyle() {
  if (!tokens) return;
  const lightLines = MANAGED_COLOR_KEYS.map(k => `  --de-${k}: ${tokens!.light[k]};`).join('\n');
  const darkLines = MANAGED_COLOR_KEYS.map(k => `  --de-${k}: ${tokens!.dark[k]};`).join('\n');
  const fontDecl = `  --de-font-primary: '${tokens.font}', system-ui, sans-serif;`;
  tokensStyle.textContent = `:root {\n${lightLines}\n${fontDecl}\n}\nhtml.de-dark {\n${darkLines}\n}\nbody { font-family: var(--de-font-primary); background: var(--de-background); color: var(--de-foreground); margin: 0; min-height: 100vh; }`;
}

function buildPage(): HTMLElement {
  if (!tokens) return document.createElement('div');
  const page = document.createElement('div');
  page.className = 'de-page';

  page.appendChild(buildHeader());
  page.appendChild(buildColorEditor());
  page.appendChild(buildFontPicker());
  page.appendChild(buildDemoShowcase());
  page.appendChild(buildCssFallback());

  return page;
}

function buildHeader(): HTMLElement {
  const header = document.createElement('header');
  header.className = 'de-header';

  const left = document.createElement('div');
  const title = document.createElement('h1');
  title.className = 'de-title';
  title.textContent = 'Design Engine Settings';
  const subtitle = document.createElement('p');
  subtitle.className = 'de-subtitle';
  subtitle.textContent = 'Edit tokens — changes save and reload automatically.';
  left.appendChild(title);
  left.appendChild(subtitle);

  const right = document.createElement('div');
  right.style.display = 'flex';
  right.style.alignItems = 'center';
  right.style.gap = '12px';

  statusEl = document.createElement('span');
  statusEl.className = 'de-status';
  statusEl.id = 'de-status';
  right.appendChild(statusEl);

  if (lastSaveError) {
    const err = document.createElement('span');
    err.className = 'de-status de-status-error';
    err.textContent = `Error: ${lastSaveError}`;
    const retry = document.createElement('button');
    retry.textContent = 'Retry';
    retry.style.marginLeft = '8px';
    retry.addEventListener('click', () => { lastSaveError = null; flushSave(); });
    err.appendChild(retry);
    right.appendChild(err);
  }

  const toggle = document.createElement('div');
  toggle.className = 'de-mode-toggle';
  for (const m of ['light', 'dark'] as Mode[]) {
    const btn = document.createElement('button');
    btn.textContent = m === 'light' ? 'Light' : 'Dark';
    if (mode === m) btn.classList.add('active');
    btn.addEventListener('click', () => { mode = m; render(); });
    toggle.appendChild(btn);
  }
  right.appendChild(toggle);

  header.appendChild(left);
  header.appendChild(right);
  return header;
}

function buildColorEditor(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = `Colors (${mode} mode)`;
  card.appendChild(h2);

  for (const key of MANAGED_COLOR_KEYS) {
    const row = document.createElement('div');
    row.className = 'de-color-row';

    const label = document.createElement('label');
    label.textContent = `--${key}`;

    const colorIn = document.createElement('input');
    colorIn.type = 'color';
    colorIn.value = tokens![mode][key];

    const textIn = document.createElement('input');
    textIn.type = 'text';
    textIn.value = tokens![mode][key];

    const onChange = (newValue: string) => {
      colorIn.value = newValue;
      textIn.value = newValue;
      updateColor(key, newValue);
    };
    colorIn.addEventListener('input', () => onChange(colorIn.value));
    textIn.addEventListener('input', () => onChange(textIn.value));
    colorIn.addEventListener('blur', () => flushSave());
    textIn.addEventListener('blur', () => flushSave());

    row.appendChild(label);
    row.appendChild(colorIn);
    row.appendChild(textIn);
    card.appendChild(row);
  }

  return card;
}

async function loadGoogleFontsCatalog(): Promise<FontEntry[]> {
  if (catalogPromise) return catalogPromise;

  try {
    const cached = sessionStorage.getItem(CATALOG_CACHE_KEY);
    if (cached) {
      const parsed = JSON.parse(cached) as FontEntry[];
      if (Array.isArray(parsed) && parsed.length > 0) {
        fontEntries = parsed;
        catalogState = 'ready';
        return parsed;
      }
    }
  } catch { /* corrupt cache — refetch */ }

  catalogPromise = (async () => {
    const res = await fetch(GOOGLE_FONTS_METADATA_URL);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const text = await res.text();
    const stripped = stripJsonPrefix(text);
    const data = JSON.parse(stripped);
    const list = Array.isArray(data?.familyMetadataList) ? data.familyMetadataList : [];
    const mapped = list
      .map(mapMetadataEntry)
      .filter((e: FontEntry | null): e is FontEntry => e !== null);
    if (mapped.length === 0) throw new Error('Empty catalog');
    try { sessionStorage.setItem(CATALOG_CACHE_KEY, JSON.stringify(mapped)); } catch { /* quota — skip cache */ }
    return mapped;
  })();
  return catalogPromise;
}

function stripJsonPrefix(raw: string): string {
  // Google's XSSI prefix is `)]}'` followed by a newline, but be tolerant of variants.
  const trimmed = raw.replace(/^﻿/, '');
  const match = trimmed.match(/^[\s\)\]\}'"]*?(\{|\[)/);
  if (match && match.index === 0) return trimmed.slice(match[0].length - 1);
  return trimmed;
}

function mapMetadataEntry(raw: any): FontEntry | null {
  if (!raw || typeof raw.family !== 'string') return null;
  const family = raw.family;
  const category = normalizeCategory(raw.category);

  const axes = Array.isArray(raw.axes) ? raw.axes : [];
  const wght = axes.find((a: any) => a?.tag === 'wght' && typeof a.min === 'number' && typeof a.max === 'number');
  if (wght) {
    return { family, category, axisRange: `${Math.round(wght.min)}..${Math.round(wght.max)}` };
  }

  const weights: number[] = [];
  if (raw.fonts && typeof raw.fonts === 'object') {
    const seen = new Set<number>();
    for (const key of Object.keys(raw.fonts)) {
      const n = parseInt(key, 10);
      if (!Number.isNaN(n) && n >= 100 && n <= 1000 && !seen.has(n)) {
        seen.add(n);
        weights.push(n);
      }
    }
    weights.sort((a, b) => a - b);
  }

  // Single regular-weight fonts (Pacifico, etc.) want no `wght` param at all.
  if (weights.length === 0 || (weights.length === 1 && weights[0] === 400)) {
    return { family, category };
  }
  return { family, category, weights };
}

function normalizeCategory(raw: any): string {
  if (typeof raw !== 'string' || !raw) return 'sans-serif';
  return raw.toLowerCase().replace(/_/g, '-');
}

function fontImportFor(f: FontEntry): { name: string; weights?: number[]; axisRange?: string } {
  return { name: f.family, weights: f.weights, axisRange: f.axisRange };
}

function buildFontPicker(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Font (shared across modes)';
  card.appendChild(h2);

  const wrap = document.createElement('div');
  wrap.className = 'de-relative';

  const input = document.createElement('input');
  input.type = 'text';
  input.className = 'de-font-input';
  input.placeholder = 'Type a font name…';
  input.value = tokens!.font;
  input.autocomplete = 'off';

  const suggestions = document.createElement('div');
  suggestions.className = 'de-font-suggestions';
  suggestions.hidden = true;

  const renderSuggestions = (q: string) => {
    while (suggestions.firstChild) suggestions.removeChild(suggestions.firstChild);
    const ql = q.toLowerCase().trim();
    const matches = fontEntries.filter(f => f.family.toLowerCase().includes(ql)).slice(0, 20);

    if (catalogState === 'loading') {
      const hint = document.createElement('div');
      hint.className = 'de-font-cat';
      hint.style.cssText = 'padding: 8px 12px;';
      hint.textContent = 'Loading Google Fonts catalog…';
      suggestions.appendChild(hint);
    }

    if (matches.length === 0 && catalogState !== 'loading') {
      suggestions.hidden = true;
      return;
    }
    suggestions.hidden = false;
    for (const f of matches) {
      const btn = document.createElement('button');
      const fam = document.createElement('span');
      fam.style.fontFamily = `'${f.family}', system-ui`;
      fam.textContent = f.family;
      const cat = document.createElement('span');
      cat.className = 'de-font-cat';
      cat.textContent = f.category;
      btn.appendChild(fam);
      btn.appendChild(cat);
      btn.addEventListener('mousedown', e => {
        e.preventDefault();
        input.value = f.family;
        updateFont(f.family, fontImportFor(f));
        suggestions.hidden = true;
        flushSave();
      });
      suggestions.appendChild(btn);
    }
  };

  const ensureCatalog = async () => {
    if (catalogState === 'ready' || catalogState === 'failed' || catalogState === 'loading') return;
    catalogState = 'loading';
    renderSuggestions(input.value);
    try {
      const entries = await loadGoogleFontsCatalog();
      fontEntries = entries;
      catalogState = 'ready';
    } catch {
      // Stay on OFFLINE_FONTS — already the default.
      catalogState = 'failed';
    }
    if (document.activeElement === input) renderSuggestions(input.value);
  };

  input.addEventListener('focus', () => {
    renderSuggestions(input.value);
    void ensureCatalog();
  });
  input.addEventListener('input', () => {
    renderSuggestions(input.value);
    // Update local preview only; defer save until blur or suggestion pick.
    if (tokens) {
      tokens.font = input.value;
      updateTokensStyle();
      const pre = document.getElementById('de-css-output');
      if (pre) pre.textContent = generateCss();
    }
  });
  input.addEventListener('blur', () => {
    const match = fontEntries.find(f => f.family.toLowerCase() === input.value.toLowerCase());
    if (match) updateFont(match.family, fontImportFor(match));
    else updateFont(input.value, null);
    setTimeout(() => { suggestions.hidden = true; }, 150);
    flushSave();
  });

  wrap.appendChild(input);
  wrap.appendChild(suggestions);
  card.appendChild(wrap);
  return card;
}

function buildDemoShowcase(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Live Preview';
  card.appendChild(h2);

  const demo = document.createElement('div');
  demo.className = 'de-demo';

  const typoSection = document.createElement('section');
  const h1 = document.createElement('h1');
  h1.style.cssText = 'font-size: 32px; font-weight: 700; margin: 0;';
  h1.textContent = 'Display heading';
  const sectionH2 = document.createElement('h2');
  sectionH2.style.cssText = 'font-size: 20px; font-weight: 600; margin: 8px 0;';
  sectionH2.textContent = 'Section heading';
  const para = document.createElement('p');
  para.style.cssText = 'font-size: 14px; margin: 8px 0;';
  para.textContent = 'Body paragraph showing how foreground color and the primary font interact at default reading size.';
  const small = document.createElement('p');
  small.style.cssText = 'font-size: 12px; opacity: 0.7; margin: 8px 0;';
  small.textContent = 'Small label / muted text';
  const code = document.createElement('code');
  code.style.cssText = 'font-size: 12px; padding: 2px 6px; background: color-mix(in oklab, var(--de-foreground) 10%, transparent); border-radius: 4px; font-family: ui-monospace, monospace;';
  code.textContent = 'inline code';
  typoSection.appendChild(h1);
  typoSection.appendChild(sectionH2);
  typoSection.appendChild(para);
  typoSection.appendChild(small);
  typoSection.appendChild(code);

  const buttonsRow = document.createElement('div');
  buttonsRow.className = 'de-demo-row';
  for (const [label, cls] of [['Brand', 'de-btn-brand'], ['Primary', 'de-btn-primary'], ['Destructive', 'de-btn-destructive'], ['Outline', 'de-btn-outline']] as const) {
    const b = document.createElement('button');
    b.className = `de-btn ${cls}`;
    b.textContent = label;
    buttonsRow.appendChild(b);
  }

  const chipsRow = document.createElement('div');
  chipsRow.className = 'de-demo-row';
  for (const [label, cls] of [['Success', 'de-chip-success'], ['Warning', 'de-chip-warning'], ['Error', 'de-chip-error'], ['Info', 'de-chip-info']] as const) {
    const c = document.createElement('span');
    c.className = `de-chip ${cls}`;
    c.textContent = label;
    chipsRow.appendChild(c);
  }

  const form = document.createElement('div');
  form.className = 'de-form';
  const input = document.createElement('input');
  input.type = 'text';
  input.placeholder = 'Text input';
  const select = document.createElement('select');
  for (const opt of ['Option A', 'Option B']) {
    const o = document.createElement('option');
    o.textContent = opt;
    select.appendChild(o);
  }
  form.appendChild(input);
  form.appendChild(select);

  const stat = document.createElement('div');
  stat.className = 'de-stat-card';
  const statLabel = document.createElement('p');
  statLabel.className = 'de-stat-label';
  statLabel.textContent = 'REVENUE';
  const statValue = document.createElement('p');
  statValue.className = 'de-stat-value';
  statValue.textContent = '$48.2K';
  const statDelta = document.createElement('p');
  statDelta.className = 'de-stat-delta';
  statDelta.textContent = '+8.2% vs last month';
  stat.appendChild(statLabel);
  stat.appendChild(statValue);
  stat.appendChild(statDelta);

  demo.appendChild(typoSection);
  demo.appendChild(buttonsRow);
  demo.appendChild(chipsRow);
  demo.appendChild(form);
  demo.appendChild(stat);
  card.appendChild(demo);
  return card;
}

function buildCssFallback(): HTMLElement {
  const card = document.createElement('div');
  card.className = 'de-card';
  const h2 = document.createElement('h2');
  h2.textContent = 'Generated CSS (fallback)';
  card.appendChild(h2);
  const note = document.createElement('p');
  note.style.cssText = 'font-size: 12px; opacity: 0.7; margin: 0 0 12px 0;';
  note.textContent = 'Live write-back is active. Use this snippet for sharing or as a fallback.';
  card.appendChild(note);
  const pre = document.createElement('pre');
  pre.className = 'de-pre';
  pre.id = 'de-css-output';
  pre.textContent = generateCss();
  card.appendChild(pre);
  const copy = document.createElement('button');
  copy.className = 'de-btn de-btn-outline';
  copy.style.marginTop = '12px';
  copy.textContent = 'Copy CSS';
  copy.addEventListener('click', () => navigator.clipboard.writeText(generateCss()));
  card.appendChild(copy);
  return card;
}

function generateCss(): string {
  if (!tokens) return '';
  const lightLines = MANAGED_COLOR_KEYS.map(k => `  --${k}: ${tokens!.light[k]};`).join('\n');
  const darkLines = MANAGED_COLOR_KEYS.map(k => `  --${k}: ${tokens!.dark[k]};`).join('\n');
  return `:root {\n${lightLines}\n  --font-primary: '${tokens.font}', system-ui, sans-serif;\n}\n\n.dark {\n${darkLines}\n}`;
}

function updateColor(key: ColorKey, value: string) {
  if (!tokens) return;
  tokens[mode][key] = value;
  updateTokensStyle();
  const pre = document.getElementById('de-css-output');
  if (pre) pre.textContent = generateCss();
  scheduleSave();
}

function updateFont(name: string, fontImport: { name: string; weights?: number[]; axisRange?: string } | null) {
  if (!tokens) return;
  tokens.font = name;
  pendingFontImport = fontImport;
  updateTokensStyle();
  const pre = document.getElementById('de-css-output');
  if (pre) pre.textContent = generateCss();
  scheduleSave();
}

function setStatus(s: 'idle' | 'saving' | 'saved') {
  if (!statusEl) return;
  if (s === 'idle') { statusEl.textContent = ''; statusEl.className = 'de-status'; return; }
  if (s === 'saving') { statusEl.textContent = 'Saving…'; statusEl.className = 'de-status de-status-saving'; return; }
  if (s === 'saved') { statusEl.textContent = 'Saved'; statusEl.className = 'de-status de-status-saved'; }
}

function scheduleSave() {
  if (saveTimer !== null) window.clearTimeout(saveTimer);
  saveTimer = window.setTimeout(() => { flushSave(); }, 250);
}

async function flushSave() {
  if (!tokens) return;
  if (saveTimer !== null) { window.clearTimeout(saveTimer); saveTimer = null; }
  setStatus('saving');
  const payload = { mode, colors: tokens[mode], font: tokens.font, fontImport: pendingFontImport };
  try {
    const res = await fetch('/__design/api/tokens', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(payload),
    });
    const body = await res.json();
    // Adopt server-canonical tokens if available, even on partial failure (207).
    if (body.tokens) tokens = body.tokens;
    if (!res.ok || !body.ok) throw new Error(body.message ?? `HTTP ${res.status}`);
    lastSaveError = null;
    updateTokensStyle();
    setStatus('saved');
    window.setTimeout(() => { if (statusEl?.textContent === 'Saved') setStatus('idle'); }, 1500);
  } catch (e) {
    lastSaveError = String((e as Error).message);
    render();
  }
  pendingFontImport = undefined;
}
