// Generated by design-engine /design-settings-page
// Server-only helper. Fetches the Google Fonts metadata endpoint
// (which is same-origin only and not CORS-exposed), normalizes the
// response to a stable internal FontEntry[] format, and caches in
// module-scope memory with a 24h TTL.
//
// Used by the dev-only /__design/api/google-fonts proxy route. The
// browser-side settings page fetches that same-origin proxy instead
// of fonts.google.com directly — see PR for issue #11 for context.

export type FontEntry = {
  family: string;
  category: string;
  weights?: number[];
  axisRange?: string;
};

const GOOGLE_FONTS_METADATA_URL = 'https://fonts.google.com/metadata/fonts';
const DEFAULT_TTL_MS = 24 * 60 * 60 * 1000;

export function parseGoogleFontsResponse(raw: string): FontEntry[] {
  const stripped = stripJsonPrefix(raw);
  const data = JSON.parse(stripped);
  const list = Array.isArray(data?.familyMetadataList) ? data.familyMetadataList : [];
  const out: FontEntry[] = [];
  for (const item of list) {
    const entry = mapMetadataEntry(item);
    if (entry) out.push(entry);
  }
  return out;
}

function stripJsonPrefix(raw: string): string {
  // Google's XSSI prefix is `)]}'` followed by a newline, but be tolerant of
  // BOMs and variants (whitespace, missing newline, partial prefix).
  const trimmed = raw.replace(/^﻿/, '');
  const match = trimmed.match(/^[\s)\]}'"]*?(\{|\[)/);
  if (match && match.index === 0) return trimmed.slice(match[0].length - 1);
  return trimmed;
}

function mapMetadataEntry(raw: any): FontEntry | null {
  if (!raw || typeof raw.family !== 'string' || raw.family.length === 0) return null;
  const family = raw.family;
  const category = normalizeCategory(raw.category);

  const axes = Array.isArray(raw.axes) ? raw.axes : [];
  const wght = axes.find((a: any) => a?.tag === 'wght' && typeof a.min === 'number' && typeof a.max === 'number');
  if (wght) {
    return { family, category, axisRange: `${Math.round(wght.min)}..${Math.round(wght.max)}` };
  }

  const weights: number[] = [];
  if (raw.fonts && typeof raw.fonts === 'object') {
    const seen = new Set<number>();
    for (const key of Object.keys(raw.fonts)) {
      const n = parseInt(key, 10);
      if (!Number.isNaN(n) && n >= 100 && n <= 1000 && !seen.has(n)) {
        seen.add(n);
        weights.push(n);
      }
    }
    weights.sort((a, b) => a - b);
  }

  // Single regular-weight fonts (Pacifico, etc.) want no `wght` param at all.
  if (weights.length === 0 || (weights.length === 1 && weights[0] === 400)) {
    return { family, category };
  }
  return { family, category, weights };
}

function normalizeCategory(raw: any): string {
  if (typeof raw !== 'string' || !raw) return 'sans-serif';
  return raw.toLowerCase().replace(/_/g, '-');
}

export type FontsCatalogFetcher = () => Promise<FontEntry[]>;

export type FontsCatalogFetcherOptions = {
  now?: () => number;
  fetchImpl?: typeof fetch;
  ttlMs?: number;
};

type CacheEntry = { fonts: FontEntry[]; storedAt: number };

export function createGoogleFontsCatalogFetcher(opts: FontsCatalogFetcherOptions = {}): FontsCatalogFetcher {
  const now = opts.now ?? (() => Date.now());
  const fetchImpl = opts.fetchImpl ?? fetch;
  const ttlMs = opts.ttlMs ?? DEFAULT_TTL_MS;

  let cache: CacheEntry | null = null;
  let inFlight: Promise<FontEntry[]> | null = null;

  async function refresh(): Promise<FontEntry[]> {
    const res = await fetchImpl(GOOGLE_FONTS_METADATA_URL);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const text = await res.text();
    const parsed = parseGoogleFontsResponse(text);
    if (parsed.length === 0) throw new Error('Empty catalog');
    cache = { fonts: parsed, storedAt: now() };
    return parsed;
  }

  // Stale-fallback lives inside the in-flight promise so all single-flight
  // awaiters resolve to the same outcome (fresh data, stale data, or reject).
  async function refreshWithStaleFallback(): Promise<FontEntry[]> {
    try {
      return await refresh();
    } catch (err) {
      if (cache) return cache.fonts;
      throw err;
    }
  }

  return async function fetchGoogleFontsCatalog(): Promise<FontEntry[]> {
    if (cache && now() - cache.storedAt < ttlMs) {
      return cache.fonts;
    }
    if (inFlight) return inFlight;
    inFlight = refreshWithStaleFallback().finally(() => { inFlight = null; });
    return inFlight;
  };
}

export const fetchGoogleFontsCatalog: FontsCatalogFetcher = createGoogleFontsCatalogFetcher();
