import { PageShell, PageContent } from "@/components/patterns/page-shell"
import { TopBar } from "@/components/patterns/top-bar"
import { BottomNav } from "@/components/patterns/bottom-nav"
import { HeroCard } from "@/components/patterns/hero-card"
import { SectionCard } from "@/components/patterns/section-card"
import { Wallet, Home, Settings } from "lucide-react"

// Generated by design-engine /design-page
// Recipe: <RECIPE_NAME>
// Adapter: react-shadcn

export default function <PAGE_NAME>() {
  return (
    <PageShell maxWidth="430px">
      <TopBar logo={<>Logo</>} subtitle="Today" />
      <PageContent>
        <HeroCard
          icon={Wallet}
          label="Primary Metric"
          value="0"
          unit=""
          trend={{ value: "+0.0%", direction: "up", label: "vs last period" }}
          watermarkIcon={Wallet}
        />
        <div className="grid grid-cols-2 gap-4 px-6">
          {/* KPI cards go here — fill in 2 or 4 per recipe */}
        </div>
        <SectionCard title="Recent Activity">
          {/* List items go here */}
        </SectionCard>
      </PageContent>
      <BottomNav
        items={[
          { name: "Home", icon: Home },
          { name: "Settings", icon: Settings },
        ]}
        activeIndex={0}
      />
    </PageShell>
  )
}
