// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Adapter: react-shadcn
// Note: This is a dev-only token viewer. Edits produce a copyable CSS snippet —
//       paste it into your theme.css to apply. Live write-back is a v0.x feature.

import * as React from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface TokenSet {
  brand: string
  primary: string
  background: string
  card: string
  foreground: string
  destructive: string
  success: string
  warning: string
  info: string
  font: string
}

const DEFAULT_TOKENS: TokenSet = {
  brand: "#721FE5",
  primary: "#030213",
  background: "#FAFAFA",
  card: "#FFFFFF",
  foreground: "#2A2A2A",
  destructive: "#d4183d",
  success: "#6B9B7A",
  warning: "#D97706",
  info: "#3B82F6",
  font: "Inter",
}

export default function DesignSettingsPage() {
  const [tokens, setTokens] = React.useState<TokenSet>(DEFAULT_TOKENS)

  const update = (key: keyof TokenSet, value: string) =>
    setTokens(prev => ({ ...prev, [key]: value }))

  const cssOutput = React.useMemo(() => generateCss(tokens), [tokens])

  const copyToClipboard = () => {
    navigator.clipboard.writeText(cssOutput)
    alert("CSS copied to clipboard. Paste into your theme.css :root block.")
  }

  const downloadCss = () => {
    const blob = new Blob([cssOutput], { type: "text/css" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "theme.css"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-[800px] mx-auto p-6 space-y-6">
      <div>
        <h1 className="text-[24px] font-bold">Design Engine Settings</h1>
        <p className="text-[14px] text-text-secondary mt-1">
          Tweak design tokens. Edits produce a copyable CSS snippet — paste into theme.css to apply.
        </p>
      </div>

      <Card className="p-6 space-y-4">
        <h2 className="text-[18px] font-bold">Colors</h2>
        {Object.entries(tokens).filter(([k]) => k !== "font").map(([key, value]) => (
          <div key={key} className="flex items-center gap-4">
            <Label className="w-32">--{key}</Label>
            <Input
              type="color"
              value={value}
              onChange={e => update(key as keyof TokenSet, e.target.value)}
              className="w-16 h-10"
            />
            <Input
              type="text"
              value={value}
              onChange={e => update(key as keyof TokenSet, e.target.value)}
              className="font-mono"
            />
          </div>
        ))}
      </Card>

      <Card className="p-6">
        <h2 className="text-[18px] font-bold mb-4">Font</h2>
        <select
          value={tokens.font}
          onChange={e => update("font", e.target.value)}
          className="w-full p-2 border rounded-md"
        >
          <option>Inter</option>
          <option>Pretendard</option>
          <option>Geist</option>
          <option>DM Sans</option>
          <option>System default</option>
        </select>
      </Card>

      <Card className="p-6">
        <h2 className="text-[18px] font-bold mb-4">Live Preview</h2>
        <div
          className="p-4 rounded-2xl"
          style={{
            background: tokens.card,
            color: tokens.foreground,
            fontFamily: tokens.font,
            boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
          }}
        >
          <p className="text-[12px] uppercase tracking-wide font-bold" style={{ color: tokens.foreground }}>SAMPLE CARD</p>
          <p className="text-[36px] font-bold" style={{ color: tokens.foreground }}>$48.2<span className="text-[18px]">K</span></p>
          <p className="text-[13px] font-bold" style={{ color: tokens.success }}>+8.2% vs last month</p>
          <button
            className="mt-4 px-4 py-2 rounded-md text-white font-medium"
            style={{ background: tokens.brand }}
          >
            Primary Action
          </button>
        </div>
      </Card>

      <Card className="p-6 space-y-4">
        <h2 className="text-[18px] font-bold">Generated CSS</h2>
        <pre className="bg-[#FAFAFA] p-4 rounded-md overflow-x-auto text-[13px]">
{cssOutput}
        </pre>
        <div className="flex gap-2">
          <Button onClick={copyToClipboard}>Copy CSS</Button>
          <Button variant="outline" onClick={downloadCss}>Download theme.css</Button>
        </div>
      </Card>
    </div>
  )
}

function generateCss(tokens: TokenSet): string {
  return `:root {
  --brand: ${tokens.brand};
  --primary: ${tokens.primary};
  --background: ${tokens.background};
  --card: ${tokens.card};
  --foreground: ${tokens.foreground};
  --destructive: ${tokens.destructive};
  --success: ${tokens.success};
  --warning: ${tokens.warning};
  --info: ${tokens.info};
  --font-primary: ${tokens.font}, system-ui, sans-serif;
}`
}
