// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Helper: parses and writes theme.css surgically; manages fonts.css @import block.
// Server-side only (Node fs). Never imported from client code.

import { readFile, writeFile, rename } from 'node:fs/promises';

export const MANAGED_COLOR_KEYS = [
  'brand', 'primary', 'background', 'card', 'foreground',
  'destructive', 'success', 'warning', 'info'
] as const;

export type ColorKey = typeof MANAGED_COLOR_KEYS[number];
export type Mode = 'light' | 'dark';
export type ColorTokens = { [K in ColorKey]: string };
export type TokenSet = {
  light: ColorTokens;
  dark: ColorTokens;
  font: string;
};

export type ParseError = 'no_root_block' | 'ambiguous_root' | 'ambiguous_dark' | 'duplicate_decl' | 'read_failed';
export type WriteError = ParseError | 'no_dark_block' | 'write_failed';
export type ParseResult = { ok: true; tokens: TokenSet } | { ok: false; error: ParseError; message: string };
export type WriteResult = { ok: true; tokens: TokenSet } | { ok: false; error: WriteError; message: string };

const MANAGED_VAR_NAMES = [...MANAGED_COLOR_KEYS, 'font-primary'] as const;
const FALLBACK_COLORS: ColorTokens = {
  brand: '#721FE5', primary: '#030213', background: '#FAFAFA', card: '#FFFFFF',
  foreground: '#2A2A2A', destructive: '#d4183d', success: '#6B9B7A',
  warning: '#D97706', info: '#3B82F6',
};
const FALLBACK_FONT = 'Inter';

export async function readTokens(themePath: string): Promise<ParseResult> {
  let raw: string;
  try { raw = await readFile(themePath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }
  return parseTokens(raw);
}

export function parseTokens(css: string): ParseResult {
  const blocks = scanTopLevelBlocks(css);
  const rootBlocks = blocks.filter(b => b.selector === ':root' && blockContainsManagedToken(css, b));
  const darkBlocks = blocks.filter(b => b.selector === '.dark' && blockContainsManagedToken(css, b));

  if (rootBlocks.length === 0) return { ok: false, error: 'no_root_block', message: 'No top-level :root block contains managed tokens.' };
  if (rootBlocks.length > 1) return { ok: false, error: 'ambiguous_root', message: `Multiple top-level :root blocks contain managed tokens (${rootBlocks.length}).` };
  if (darkBlocks.length > 1) return { ok: false, error: 'ambiguous_dark', message: `Multiple top-level .dark blocks contain managed tokens (${darkBlocks.length}).` };

  const lightBody = css.slice(rootBlocks[0].bodyStart, rootBlocks[0].bodyEnd);
  const lightDecls = scanDeclarations(lightBody);
  if (hasDuplicates(lightDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in :root block.' };

  const lightColors: ColorTokens = { ...FALLBACK_COLORS };
  let font = FALLBACK_FONT;
  for (const d of lightDecls) {
    if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (lightColors as any)[d.name] = d.value;
    else if (d.name === 'font-primary') font = parseFontPrimary(d.value);
  }

  let darkColors: ColorTokens = { ...lightColors };
  if (darkBlocks.length === 1) {
    const darkBody = css.slice(darkBlocks[0].bodyStart, darkBlocks[0].bodyEnd);
    const darkDecls = scanDeclarations(darkBody);
    if (hasDuplicates(darkDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in .dark block.' };
    for (const d of darkDecls) {
      if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (darkColors as any)[d.name] = d.value;
    }
  }

  return { ok: true, tokens: { light: lightColors, dark: darkColors, font } };
}

export type Block = { selector: ':root' | '.dark'; headerStart: number; bodyStart: number; bodyEnd: number };

export function scanTopLevelBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  let i = 0;
  let depth = 0;

  while (i < css.length) {
    const c = css[i];

    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }

    if (c === '{') { depth++; i++; continue; }
    if (c === '}') { depth--; i++; continue; }

    if (depth === 0) {
      const remaining = css.slice(i);
      const rootMatch = remaining.match(/^:root(?=\s*\{)/);
      const darkMatch = remaining.match(/^\.dark(?=\s*\{)/);
      const match = rootMatch ?? darkMatch;
      if (match) {
        const headerStart = i;
        const openIdx = css.indexOf('{', i);
        if (openIdx === -1) break;
        const closeIdx = findMatchingBrace(css, openIdx);
        if (closeIdx === -1) break;
        blocks.push({
          selector: rootMatch ? ':root' : '.dark',
          headerStart,
          bodyStart: openIdx + 1,
          bodyEnd: closeIdx,
        });
        i = closeIdx + 1;
        continue;
      }
    }

    i++;
  }
  return blocks;
}

function findMatchingBrace(css: string, openIdx: number): number {
  let depth = 1;
  let i = openIdx + 1;
  while (i < css.length) {
    const c = css[i];
    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return i;
    }
    i++;
  }
  return -1;
}

export type Declaration = {
  name: string;
  value: string;
  valueStart: number;
  valueEnd: number;
};

export function scanDeclarations(body: string): Declaration[] {
  const decls: Declaration[] = [];
  let i = 0;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    // Skip strings — declaration values like `content: "--brand: #fff"` must not register as managed declarations.
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '-' && body[i + 1] === '-') {
      const decl = parseDeclarationAt(body, i);
      if (decl && (MANAGED_VAR_NAMES as readonly string[]).includes(decl.name)) {
        decls.push(decl);
        i = decl.valueEnd + 1;
        continue;
      }
    }
    i++;
  }
  return decls;
}

function parseDeclarationAt(body: string, start: number): Declaration | null {
  const colonIdx = findColonSkippingCommentsAndStrings(body, start);
  if (colonIdx === -1) return null;
  const name = body.slice(start + 2, colonIdx).trim();
  if (!/^[a-z][a-z0-9-]*$/i.test(name)) return null;
  let valueStart = colonIdx + 1;
  while (valueStart < body.length && /\s/.test(body[valueStart])) valueStart++;
  const semiIdx = findSemicolonSkippingStrings(body, valueStart);
  if (semiIdx === -1) return null;
  const value = body.slice(valueStart, semiIdx).trim();
  return { name, value, valueStart, valueEnd: semiIdx };
}

function findColonSkippingCommentsAndStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ':') return i;
    if (c === ';' || c === '{' || c === '}' || c === '\n') return -1;
    i++;
  }
  return -1;
}

function findSemicolonSkippingStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ';' || c === '}') return c === ';' ? i : -1;
    i++;
  }
  return -1;
}

function blockContainsManagedToken(css: string, block: Block): boolean {
  const body = css.slice(block.bodyStart, block.bodyEnd);
  return scanDeclarations(body).length > 0;
}

function hasDuplicates(decls: Declaration[]): boolean {
  const seen = new Set<string>();
  for (const d of decls) {
    if (seen.has(d.name)) return true;
    seen.add(d.name);
  }
  return false;
}

function parseFontPrimary(raw: string): string {
  const first = raw.split(',')[0].trim();
  return first.replace(/^['"]|['"]$/g, '');
}
