// Originally from bitjaru/styleseed (MIT) — see /LICENSE for full attribution.
// Ported to design-engine plugin under MIT.
//
// Generated by design-engine /design-settings-page
// Helper: parses and writes theme.css surgically; manages fonts.css @import block.
// Server-side only (Node fs). Never imported from client code.

import { readFile, writeFile, rename } from 'node:fs/promises';

export const MANAGED_COLOR_KEYS = [
  'brand', 'primary', 'background', 'card', 'foreground',
  'destructive', 'success', 'warning', 'info'
] as const;

export type ColorKey = typeof MANAGED_COLOR_KEYS[number];
export type Mode = 'light' | 'dark';
export type ColorTokens = { [K in ColorKey]: string };
export type TokenSet = {
  light: ColorTokens;
  dark: ColorTokens;
  font: string;
};

export type ParseError = 'no_root_block' | 'ambiguous_root' | 'ambiguous_dark' | 'duplicate_decl' | 'read_failed';
export type WriteError = ParseError | 'no_dark_block' | 'write_failed';
export type ParseResult = { ok: true; tokens: TokenSet } | { ok: false; error: ParseError; message: string };
export type WriteResult = { ok: true; tokens: TokenSet } | { ok: false; error: WriteError; message: string };

const MANAGED_VAR_NAMES = [...MANAGED_COLOR_KEYS, 'font-primary'] as const;
const FALLBACK_COLORS: ColorTokens = {
  brand: '#721FE5', primary: '#030213', background: '#FAFAFA', card: '#FFFFFF',
  foreground: '#2A2A2A', destructive: '#d4183d', success: '#6B9B7A',
  warning: '#D97706', info: '#3B82F6',
};
const FALLBACK_FONT = 'Inter';

export async function readTokens(themePath: string): Promise<ParseResult> {
  let raw: string;
  try { raw = await readFile(themePath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }
  return parseTokens(raw);
}

export function parseTokens(css: string): ParseResult {
  const blocks = scanTopLevelBlocks(css);
  const rootBlocks = blocks.filter(b => b.selector === ':root' && blockContainsManagedToken(css, b));
  const darkBlocks = blocks.filter(b => b.selector === '.dark' && blockContainsManagedToken(css, b));

  if (rootBlocks.length === 0) return { ok: false, error: 'no_root_block', message: 'No top-level :root block contains managed tokens.' };
  if (rootBlocks.length > 1) return { ok: false, error: 'ambiguous_root', message: `Multiple top-level :root blocks contain managed tokens (${rootBlocks.length}).` };
  if (darkBlocks.length > 1) return { ok: false, error: 'ambiguous_dark', message: `Multiple top-level .dark blocks contain managed tokens (${darkBlocks.length}).` };

  const lightBody = css.slice(rootBlocks[0].bodyStart, rootBlocks[0].bodyEnd);
  const lightDecls = scanDeclarations(lightBody);
  if (hasDuplicates(lightDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in :root block.' };

  const lightColors: ColorTokens = { ...FALLBACK_COLORS };
  let font = FALLBACK_FONT;
  for (const d of lightDecls) {
    if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (lightColors as any)[d.name] = d.value;
    else if (d.name === 'font-primary') font = parseFontPrimary(d.value);
  }

  let darkColors: ColorTokens = { ...lightColors };
  if (darkBlocks.length === 1) {
    const darkBody = css.slice(darkBlocks[0].bodyStart, darkBlocks[0].bodyEnd);
    const darkDecls = scanDeclarations(darkBody);
    if (hasDuplicates(darkDecls)) return { ok: false, error: 'duplicate_decl', message: 'Duplicate managed variable in .dark block.' };
    for (const d of darkDecls) {
      if ((MANAGED_COLOR_KEYS as readonly string[]).includes(d.name)) (darkColors as any)[d.name] = d.value;
    }
  }

  return { ok: true, tokens: { light: lightColors, dark: darkColors, font } };
}

export type Block = { selector: ':root' | '.dark'; headerStart: number; bodyStart: number; bodyEnd: number };

export function scanTopLevelBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  let i = 0;
  let depth = 0;

  while (i < css.length) {
    const c = css[i];

    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }

    if (c === '{') { depth++; i++; continue; }
    if (c === '}') { depth--; i++; continue; }

    if (depth === 0) {
      const remaining = css.slice(i);
      const rootMatch = remaining.match(/^:root(?=\s*\{)/);
      const darkMatch = remaining.match(/^\.dark(?=\s*\{)/);
      const match = rootMatch ?? darkMatch;
      if (match) {
        const headerStart = i;
        const openIdx = css.indexOf('{', i);
        if (openIdx === -1) break;
        const closeIdx = findMatchingBrace(css, openIdx);
        if (closeIdx === -1) break;
        blocks.push({
          selector: rootMatch ? ':root' : '.dark',
          headerStart,
          bodyStart: openIdx + 1,
          bodyEnd: closeIdx,
        });
        i = closeIdx + 1;
        continue;
      }
    }

    i++;
  }
  return blocks;
}

function findMatchingBrace(css: string, openIdx: number): number {
  let depth = 1;
  let i = openIdx + 1;
  while (i < css.length) {
    const c = css[i];
    if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return i;
    }
    i++;
  }
  return -1;
}

export type Declaration = {
  name: string;
  value: string;
  valueStart: number;
  valueEnd: number;
};

export function scanDeclarations(body: string): Declaration[] {
  const decls: Declaration[] = [];
  let i = 0;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    // Skip strings — declaration values like `content: "--brand: #fff"` must not register as managed declarations.
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === '-' && body[i + 1] === '-') {
      const decl = parseDeclarationAt(body, i);
      if (decl && (MANAGED_VAR_NAMES as readonly string[]).includes(decl.name)) {
        decls.push(decl);
        i = decl.valueEnd + 1;
        continue;
      }
    }
    i++;
  }
  return decls;
}

function parseDeclarationAt(body: string, start: number): Declaration | null {
  const colonIdx = findColonSkippingCommentsAndStrings(body, start);
  if (colonIdx === -1) return null;
  const name = body.slice(start + 2, colonIdx).trim();
  if (!/^[a-z][a-z0-9-]*$/i.test(name)) return null;
  let valueStart = colonIdx + 1;
  while (valueStart < body.length && /\s/.test(body[valueStart])) valueStart++;
  const semiIdx = findSemicolonSkippingStrings(body, valueStart);
  if (semiIdx === -1) return null;
  const value = body.slice(valueStart, semiIdx).trim();
  return { name, value, valueStart, valueEnd: semiIdx };
}

function findColonSkippingCommentsAndStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ':') return i;
    if (c === ';' || c === '{' || c === '}' || c === '\n') return -1;
    i++;
  }
  return -1;
}

function findSemicolonSkippingStrings(body: string, from: number): number {
  let i = from;
  while (i < body.length) {
    const c = body[i];
    if (c === '/' && body[i + 1] === '*') {
      const end = body.indexOf('*/', i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const quote = c;
      i++;
      while (i < body.length && body[i] !== quote) {
        if (body[i] === '\\') i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === ';' || c === '}') return c === ';' ? i : -1;
    i++;
  }
  return -1;
}

function blockContainsManagedToken(css: string, block: Block): boolean {
  const body = css.slice(block.bodyStart, block.bodyEnd);
  return scanDeclarations(body).length > 0;
}

function hasDuplicates(decls: Declaration[]): boolean {
  const seen = new Set<string>();
  for (const d of decls) {
    if (seen.has(d.name)) return true;
    seen.add(d.name);
  }
  return false;
}

function parseFontPrimary(raw: string): string {
  const first = raw.split(',')[0].trim();
  return first.replace(/^['"]|['"]$/g, '');
}

async function atomicWrite(filePath: string, contents: string): Promise<void> {
  const tmp = filePath + '.tmp';
  await writeFile(tmp, contents, 'utf8');
  let lastErr: unknown;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      await rename(tmp, filePath);
      return;
    } catch (e: any) {
      lastErr = e;
      if (e?.code !== 'EBUSY' && e?.code !== 'EPERM' && e?.code !== 'EACCES') throw e;
      await new Promise(r => setTimeout(r, 50));
    }
  }
  throw lastErr;
}

export async function writeTokens(themePath: string, mode: Mode, colors: ColorTokens, font?: string): Promise<WriteResult> {
  let raw: string;
  try { raw = await readFile(themePath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }

  const blocks = scanTopLevelBlocks(raw);
  const targetSelector = mode === 'light' ? ':root' : '.dark';
  const targets = blocks.filter(b => b.selector === targetSelector && blockContainsManagedToken(raw, b));

  if (targets.length === 0) return { ok: false, error: mode === 'light' ? 'no_root_block' : 'no_dark_block', message: `No ${targetSelector} block with managed tokens.` };
  if (targets.length > 1) return { ok: false, error: mode === 'light' ? 'ambiguous_root' : 'ambiguous_dark', message: `Multiple ${targetSelector} blocks with managed tokens.` };

  const block = targets[0];
  const bodyStart = block.bodyStart;
  const bodyEnd = block.bodyEnd;
  const body = raw.slice(bodyStart, bodyEnd);
  const decls = scanDeclarations(body);

  const wantedReplacements = new Map<string, string>();
  for (const k of MANAGED_COLOR_KEYS) wantedReplacements.set(k, colors[k]);
  if (mode === 'light' && font !== undefined) wantedReplacements.set('font-primary', formatFontPrimary(font));

  const allKeys: readonly string[] = mode === 'light' ? [...MANAGED_COLOR_KEYS, 'font-primary'] : MANAGED_COLOR_KEYS;

  let newBody = body;
  const orderedExisting = decls
    .filter(d => wantedReplacements.has(d.name))
    .sort((a, b) => b.valueStart - a.valueStart);
  for (const d of orderedExisting) {
    const newValue = wantedReplacements.get(d.name)!;
    newBody = newBody.slice(0, d.valueStart) + newValue + newBody.slice(d.valueEnd);
    wantedReplacements.delete(d.name);
  }

  if (wantedReplacements.size > 0) {
    const trailingMatch = newBody.match(/(\s*)$/);
    const trailing = trailingMatch?.[1] ?? '';
    const insertAt = newBody.length - trailing.length;
    const missing = Array.from(wantedReplacements.entries())
      .filter(([k]) => allKeys.includes(k))
      .map(([k, v]) => `\n  --${k}: ${v};`)
      .join('');
    newBody = newBody.slice(0, insertAt) + missing + newBody.slice(insertAt);
  }

  const newRaw = raw.slice(0, bodyStart) + newBody + raw.slice(bodyEnd);

  try { await atomicWrite(themePath, newRaw); }
  catch (e) { return { ok: false, error: 'write_failed', message: String(e) }; }

  const reread = await readTokens(themePath);
  if (!reread.ok) return { ok: false, error: 'write_failed', message: 'Wrote file but failed to re-read: ' + reread.message };
  return { ok: true, tokens: reread.tokens };
}

function formatFontPrimary(name: string): string {
  const needsQuotes = /[^a-zA-Z0-9-]/.test(name);
  const quoted = needsQuotes ? `'${name}'` : name;
  return `${quoted}, system-ui, -apple-system, BlinkMacSystemFont, sans-serif`;
}

export type FontImportEntry = {
  name: string;
  url: string;
};

const FONT_BLOCK_START = '/* design-engine: managed-font-imports:start */';
const FONT_BLOCK_END = '/* design-engine: managed-font-imports:end */';

export type FontImportResult = { ok: true } | { ok: false; error: string; message: string };

export async function writeFontImports(fontsPath: string, entries: FontImportEntry[]): Promise<FontImportResult> {
  let raw: string;
  try { raw = await readFile(fontsPath, 'utf8'); }
  catch (e) { return { ok: false, error: 'read_failed', message: String(e) }; }

  const newBlock = renderFontImportBlock(entries);
  const startIdx = raw.indexOf(FONT_BLOCK_START);
  const endIdx = raw.indexOf(FONT_BLOCK_END);

  let newRaw: string;
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const blockEnd = endIdx + FONT_BLOCK_END.length;
    newRaw = raw.slice(0, startIdx) + newBlock + raw.slice(blockEnd);
  } else {
    newRaw = newBlock + '\n\n' + raw;
  }

  try { await atomicWrite(fontsPath, newRaw); }
  catch (e) { return { ok: false, error: 'write_failed', message: String(e) }; }
  return { ok: true };
}

function renderFontImportBlock(entries: FontImportEntry[]): string {
  const lines = entries.map(e => `@import url('${e.url}');`).join('\n');
  return `${FONT_BLOCK_START}\n${lines}${lines ? '\n' : ''}${FONT_BLOCK_END}`;
}

export function buildGoogleFontsUrl(family: string, weights?: number[], axisRange?: string): string {
  const familyParam = family.replace(/ /g, '+');
  let suffix = '';
  if (axisRange) suffix = `:wght@${axisRange}`;
  else if (weights && weights.length) suffix = `:wght@${weights.join(';')}`;
  return `https://fonts.googleapis.com/css2?family=${familyParam}${suffix}&display=swap`;
}
